# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 The SlicerX contributors
# fixtures/preset-files/prusaslicer-2.9.6.3mf. Builds the input for PrusaSlicer's command line: a 3MF with one
# object made of a 20 mm cube part and a smaller modifier cube, with per-object and per-volume settings in
# Slic3r_PE_model.config, and a configuration to load. Then, with PrusaSlicer 2.9.6:
#
#   python3 make-prusa-project.py                     # writes in.3mf and my.ini
#   PrusaSlicer --datadir data --load my.ini --export-3mf --output prusa-2.9.6.3mf in.3mf
#   PrusaSlicer --datadir data --load my.ini --save full.ini
#   python3 make-prusa-project.py add-config          # writes prusaslicer-2.9.6.3mf
#
# PrusaSlicer's --export-3mf writes the model and Slic3r_PE_model.config but leaves the print config out (the command
# line passes no config to store_3mf). The last step adds it as Metadata/Slic3r_PE.config the way the app writes it
# when it saves a project: a "; generated by" line, a blank line, then every key of the full configuration the command
# line saved, as "; key = value", sorted, with the wipe tower position. PrusaSlicer slices the result with that config.
import shutil
import sys
import zipfile

if len(sys.argv) > 1 and sys.argv[1] == 'add-config':
    lines = [l.rstrip('\n') for l in open('full.ini') if l.strip() and not l.startswith('#')]
    head = [l for l in open('full.ini') if l.startswith('# generated by')][0][2:].strip()
    body = sorted(['; ' + l for l in lines] + ['; wipe_tower_x = 170', '; wipe_tower_y = 140', '; wipe_tower_rotation_angle = 0'])
    shutil.copy('prusa-2.9.6.3mf', 'prusaslicer-2.9.6.3mf')
    with zipfile.ZipFile('prusaslicer-2.9.6.3mf', 'a', zipfile.ZIP_DEFLATED) as z:
        z.writestr('Metadata/Slic3r_PE.config', '; %s\n\n' % head + '\n'.join(body) + '\n')
    sys.exit(0)

def cube(x0, y0, z0, s):
    v = [(x0 + dx * s, y0 + dy * s, z0 + dz * s) for dz in (0, 1) for dy in (0, 1) for dx in (0, 1)]
    t = [(0, 2, 1), (1, 2, 3), (4, 5, 6), (5, 7, 6), (0, 1, 4), (1, 5, 4), (2, 6, 3), (3, 6, 7), (0, 4, 2), (2, 4, 6), (1, 3, 5), (3, 7, 5)]
    return v, t

pv, pt = cube(0, 0, 0, 20)
mv, mt = cube(5, 5, 5, 10)
verts = pv + mv
tris = pt + [(a + 8, b + 8, c + 8) for a, b, c in mt]
vx = ''.join(f'<vertex x="{x}" y="{y}" z="{z}"/>' for x, y, z in verts)
tx = ''.join(f'<triangle v1="{a}" v2="{b}" v3="{c}"/>' for a, b, c in tris)
model = f'''<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:slic3rpe="http://schemas.slic3r.org/3mf/2017/06">
 <metadata name="slic3rpe:Version3mf">1</metadata>
 <resources><object id="1" type="model"><mesh><vertices>{vx}</vertices><triangles>{tx}</triangles></mesh></object></resources>
 <build><item objectid="1" transform="1 0 0 0 1 0 0 0 1 100 100 0" printable="1"/></build>
</model>'''
cfg = '''<?xml version="1.0" encoding="UTF-8"?>
<config>
 <object id="1" instances_count="1">
  <metadata type="object" key="name" value="Cube with modifier"/>
  <metadata type="object" key="layer_height" value="0.15"/>
  <metadata type="object" key="perimeters" value="4"/>
  <metadata type="object" key="fill_pattern" value="gyroid"/>
  <volume firstid="0" lastid="11">
   <metadata type="volume" key="name" value="Cube"/>
   <metadata type="volume" key="volume_type" value="ModelPart"/>
   <metadata type="volume" key="matrix" value="1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"/>
  </volume>
  <volume firstid="12" lastid="23">
   <metadata type="volume" key="name" value="Denser core"/>
   <metadata type="volume" key="modifier" value="1"/>
   <metadata type="volume" key="volume_type" value="ParameterModifier"/>
   <metadata type="volume" key="matrix" value="1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"/>
   <metadata type="volume" key="fill_density" value="40%"/>
   <metadata type="volume" key="infill_speed" value="120"/>
  </volume>
 </object>
</config>'''
types = '<?xml version="1.0" encoding="UTF-8"?>\n<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/></Types>'
rels = '<?xml version="1.0" encoding="UTF-8"?>\n<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Target="/3D/3dmodel.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>'
with zipfile.ZipFile('in.3mf', 'w', zipfile.ZIP_DEFLATED) as z:
    z.writestr('[Content_Types].xml', types)
    z.writestr('_rels/.rels', rels)
    z.writestr('3D/3dmodel.model', model)
    z.writestr('Metadata/Slic3r_PE_model.config', cfg)

# A user's configuration: an MK4S-like printer with a few changed print and filament values.
open('my.ini', 'w').write('''bed_shape = 0x0,250x0,250x210,0x210
max_print_height = 220
nozzle_diameter = 0.4
printer_model = MK4S
printer_settings_id = My MK4S
print_settings_id = 0.20mm SPEED My
filament_settings_id = "My PETG"
gcode_flavor = marlin2
layer_height = 0.2
first_layer_height = 0.2
perimeters = 3
fill_density = 20%
fill_pattern = grid
support_material = 1
support_material_auto = 1
support_material_style = organic
seam_position = rear
ironing = 1
ironing_type = top
first_layer_speed = 50%
perimeter_speed = 60
infill_speed = 200
overhang_speed_0 = 15
fan_always_on = 1
infill_every_layers = 2
filament_type = PETG
temperature = 240
first_layer_temperature = 235
bed_temperature = 85
first_layer_bed_temperature = 80
filament_max_volumetric_speed = 12
filament_spool_weight = 230
travel_ramping_lift = 1
wipe_tower = 1
''')
