// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
// edition-config resolve|check|schema|neutral|tauri|expo|well-known. Run with Node 24+ (type stripping).
import { spawnSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { z } from 'zod'
import { DESKTOP_ICON_DIR, expoConfig, tauriConfig, wellKnown } from './build.ts'
import { NEUTRAL_EDITION } from './defaults.ts'
import { EditionConfigError, parseEditionConfig } from './define.ts'
import { missingFonts } from './fonts.ts'
import { editionAssetPath, editionFontFiles, loadEditionConfig } from './node.ts'
import { editionConfigSchema } from './schema.ts'

const [cmd, file, extra, out] = process.argv.slice(2)
const load = () => loadEditionConfig(file ? { file } : {})

try {
  switch (cmd) {
    case 'resolve':
      // The resolved JSON is what Rust services read (sx-edition-config) and what deployments ship.
      process.stdout.write(JSON.stringify(await load(), null, 2) + '\n')
      break
    case 'check': {
      const config = await load()
      const named = file ?? process.env['SLICERX_CONFIG']
      if (named) editionFontFiles(config, named)
      for (const f of missingFonts(config)) console.warn(`warning: font "${f}" is not bundled; add it to brand.theme.tokens.fontFiles or text falls back to the system sans-serif`)
      console.log('edition config is valid')
      break
    }
    case 'schema':
      process.stdout.write(JSON.stringify(z.toJSONSchema(editionConfigSchema, { io: 'input', unrepresentable: 'any' }), null, 2) + '\n')
      break
    case 'neutral':
      // The parsed neutral config as a typed constant, so a running app needs no parser for it.
      process.stdout.write(`// SPDX-License-Identifier: Apache-2.0\n// Copyright (C) 2026 The SlicerX contributors\n// Generated by \`node src/cli.ts neutral\`; do not edit. The test pins it to parseEditionConfig(NEUTRAL_EDITION).\nimport type { EditionConfig } from './schema.ts'\n\nexport const NEUTRAL_PARSED: EditionConfig = ${JSON.stringify(parseEditionConfig(NEUTRAL_EDITION), null, 2)}\n`)
      break
    case 'tauri': {
      // SLICERX_CONFIG wins over the default file the build script passes; `out` writes the file itself, so no shell redirect is needed on Windows.
      const named = process.env['SLICERX_CONFIG'] || file
      const config = await loadEditionConfig(named ? { file: named } : {})
      const target = extra === 'mobile' ? 'mobile' : 'desktop'
      const text = JSON.stringify(tauriConfig(config, target), null, 2) + '\n'
      if (out) {
        mkdirSync(dirname(out), { recursive: true })
        writeFileSync(out, text)
      } else process.stdout.write(text)
      // The overlay points the bundle at icons made from the edition's appIcon; make them next to it.
      // `out` sits in src-tauri/gen, and the icon paths are relative to src-tauri.
      const icon = named && config.brand.logo.appIcon ? editionAssetPath(named, config.brand.logo.appIcon) : null
      if (target === 'desktop' && out && config.brand.logo.appIcon) {
        if (!icon) throw new Error('brand.logo.appIcon must be a file next to the config for the desktop build')
        const dir = join(dirname(out), '..', DESKTOP_ICON_DIR)
        const r = spawnSync('tauri', ['icon', icon, '--output', dir], { stdio: 'inherit', shell: process.platform === 'win32' })
        if (r.status !== 0) throw new Error(`tauri icon failed for ${icon}`)
      }
      break
    }
    case 'expo':
      // For Expo's app.config.ts, which must be synchronous: run this and spread the JSON.
      process.stdout.write(JSON.stringify(expoConfig(await load()), null, 2) + '\n')
      break
    case 'well-known': {
      const dir = extra ?? 'public/.well-known'
      mkdirSync(dir, { recursive: true })
      for (const [name, body] of Object.entries(wellKnown(await load()))) writeFileSync(join(dir, name), JSON.stringify(body, null, 2) + '\n')
      break
    }
    default:
      console.error('usage: edition-config <resolve|check|schema|neutral|tauri|expo|well-known> [config file] [desktop|mobile|out dir] [out file]')
      process.exit(2)
  }
} catch (e) {
  console.error(e instanceof EditionConfigError ? e.message : String(e))
  process.exit(1)
}
