// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
// Reading the config inside a running build (browser, webview, phone app). No zod here: the build
// validated the config with parseEditionConfig before it baked it in, so a running app only checks
// the shape and keeps zod out of its startup bundle.
import { EDITION_GLOBAL } from './build.ts'
import { NEUTRAL_PARSED } from './neutral.generated.ts'
import type { EditionConfig, EditionFeature, PrinterFamily } from './schema.ts'
import { EDITION_SCHEMA_VERSION } from './version.ts'

declare const __SX_EDITION__: unknown

/** True for an object that went through parseEditionConfig at build time. */
export function looksParsed(v: unknown): v is EditionConfig {
  if (!v || typeof v !== 'object') return false
  const c = v as Record<string, unknown>
  return c['schemaVersion'] === EDITION_SCHEMA_VERSION && typeof c['id'] === 'string' && typeof c['brand'] === 'object' && typeof c['features'] === 'object' && typeof c['apps'] === 'object'
}

/** The config the bundler baked in with viteDefines(). Throws when the build did not define it. */
export function editionFromBuild(): EditionConfig {
  if (typeof __SX_EDITION__ === 'undefined') throw new Error(`${EDITION_GLOBAL} is not defined; add viteDefines(config) to the build`)
  if (!looksParsed(__SX_EDITION__)) throw new Error(`${EDITION_GLOBAL} is not a parsed edition config; viteDefines() takes the output of loadEditionConfig or parseEditionConfig`)
  return __SX_EDITION__
}

/** The neutral defaults, already parsed (generated by `node src/cli.ts neutral`). What an app shows without an edition. */
export function neutralEdition(): EditionConfig {
  return NEUTRAL_PARSED
}

export function isEnabled(config: EditionConfig, feature: EditionFeature): boolean {
  return config.features[feature]
}

export function printerEnabled(config: EditionConfig, family: PrinterFamily): boolean {
  return config.features.printers[family]
}

/** Pre-alpha builds require crash reports: the setting is locked on and the first-run agreement says so. */
export function crashReportsRequired(config: EditionConfig): boolean {
  return config.release.stage === 'pre-alpha'
}

