// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
// @slicerx/app: the SlicerX shell and base workspaces. Features (the app's own
// in src/features, and edition features elsewhere) use only this entry point.
export { SlicerXApp } from './app'
export { useHost } from './host'
export { registerChatGpt, type ChatGptHost, type ChatGptAccount } from './pilot-connect/chatgpt'
export { registerLocalAi, type LocalAiHost } from './pilot-connect/local-ai-host'
export type { Hardware, LocalNet } from '@slicerx/pilot/local-ai'
export { registerAgentInstall, registerAgentMarks, type AgentInstallHost, type AgentId, type InstallResult } from './pilot-connect/agents'
export { registerCommand, registerCommands, listCommands, searchCommands, runCommand, commandTools, commandIdForTool } from './commands/registry'
export { fuzzyScore } from './commands/fuzzy'
export { setWorkspace, toast, useApp } from './state/store'
export { openModelBytes, loadDemoModel, askApproval, buildApproval } from './state/actions'
export { DEMO_MODELS, DEFAULT_MODEL, type DemoModel } from './lib/demo-models'
export { LayerArt, Swatch } from './parts'
export { setVendorMarks, VendorMark } from './lib/vendor-mark'
export { useEdition, editionTheme, appName, branded, setCurrentEdition } from './edition'
export { editionLogo, EditionMark } from './shell/edition-logo'
export { useTabLabel } from './first-run/look'
export { setSliceNote } from './lib/slice-note'
export { setExportIdentity } from './export/identity'
export type { ModelSource } from './state/store'
export { registerLinkOpener } from './lib/links'
export { reportSignInResult, type SignInResult } from './lib/sign-in-result'
export { onWindowTitle } from './project/title'
export { registerNativeMenu, type CommandEntry, type MenuEntry, type MenuSection, type NativeMenu } from './commands/menu'
export { registerPresetImport, type InstalledPreset, type PresetImportHost, type SlicerApp } from './first-run/preset-import'
export { configureRelayTokens, pushAccountToken } from './features/phone/remote'
export { setPairStorage, type PairStorage } from './features/phone/wire'
export { sealedPairStores, browserDocStore, type DocStore } from './features/phone/sealed'
export { setPhoneAccess, type PhoneAccess, type PhoneState, type PhoneDevice } from './lib/phone'
export { closeSettings, openSettings } from './state/store'
export { connectPinned, shellLinkOptions, HUB_MISMATCH, HubMismatchError, localHubPins, type HubPins } from './link/hub-pin'
export { setBridgeConnector, type BridgeConnector } from './link/connector'
export type { BridgeSetup, ConnectedBridge } from './link/bridge'
export { confirmDiscard, isDirty, onDirtyChange } from './project/unsaved'
export { registerShellGpu } from './viewport/shell-gpu'
export { holdUpdates, registerUpdater } from './updates/hold'
export type { FoundUpdate, UpdaterHost } from './updates/updates'
export { registerCrashHost, type CrashHost, type NativeCrash, type NativeCrashes } from './bugs/crash'
export { registerShellArch, type ShellArch } from './link/watch-support'
export { coverForFile, coverInColors, currentProjectUpload, fileModel, projectHasModels, projectModel, vaultCreatorsInFile, type CoverImage, type DerivedColors, type ProjectUpload, type UploadModel } from './export/upload-entry'
