# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 The SlicerX contributors
"""Adapters that turn one STL into one G-code file with each slicer's command line.

SlicerX and OrcaSlicer read the STL directly. Bambu Studio only slices 3MF projects from the
command line, and it ignores a project that lacks a complete settings block, so its project is
built here from settings resolved out of the user's own installed Bambu Studio presets at run
time. Nothing from those presets is stored in this repository.
"""
import datetime
import json
import os
import platform
import re
import shutil
import struct
import subprocess
import sys
import zipfile

import settings


def _first_existing(paths):
    for p in paths:
        if p and os.path.exists(os.path.expanduser(p)):
            return os.path.expanduser(p)
    return None


def _write_json(path, obj):
    with open(path, "w") as f:
        json.dump(obj, f)


class Job:
    """One command line plus where its outputs land."""

    def __init__(self, cmd, gcode, stdout=None, log=None):
        self.cmd, self.gcode, self.stdout, self.log = cmd, gcode, stdout, log


def slice_trusted(sx_path, stl, cfg, gcode, bed=None):
    """Slices one model with `cfg` as the person's own settings, so its custom G-code is trusted (a plain
    `sx slice` treats it as untrusted and refuses commands such as M211 and M500), and writes `gcode`.
    `bed` is (width, depth) in mm: the model is centered on that bed, as on a 256 mm one without it."""
    base = os.path.splitext(gcode)[0]
    req, out = base + "-request.json", base + "-out"
    plate = {"objects": [{"id": "o1", "name": "model", "mesh": "model"}]}
    if bed:
        plate["bed"] = {"widthMm": bed[0], "depthMm": bed[1], "heightMm": 250}
    _write_json(req, {"schemaVersion": 1, "meshes": {"model": os.path.abspath(stl)},
                      "plate": plate,
                      "config": cfg, "options": {"trustedGcode": True}})
    r = subprocess.run([sx_path, "slice", "--request", req, "--out-dir", out], capture_output=True, text=True)
    made = sorted(f for f in os.listdir(out) if f.endswith(".gcode")) if os.path.isdir(out) else []
    if r.returncode == 0 and made:
        shutil.move(os.path.join(out, made[0]), gcode)
    return r


class SlicerX:
    name = "SlicerX"
    key = "sx"

    def __init__(self, path=None):
        here = os.path.dirname(os.path.abspath(__file__))
        root = os.path.abspath(os.path.join(here, "..", "..", "..", ".."))
        exe = "sx.exe" if os.name == "nt" else "sx"
        self.path = path or os.environ.get("SX_BIN") or _first_existing([
            os.path.join(root, "target", "bench-release", exe), os.path.join(root, "target", "release", exe)]) or shutil.which("sx")
        self.version = None

    def available(self):
        return bool(self.path)

    def prepare(self, work, models):
        self.config = os.path.join(work, "sx-config.json")
        _write_json(self.config, settings.sx_config())
        self.work = work
        self.version = "sx-core (from G-code header)"

    def job(self, model, out_dir, tag="run"):
        gcode = os.path.join(out_dir, f"{model}-sx.gcode")
        return Job([self.path, "slice", self.stl(model), "--config", self.config, "-o", gcode], gcode, stdout=os.path.join(out_dir, f"{model}-sx.out"))

    def stl(self, model):
        return os.path.join(self.work, "models", f"{model}.stl")

    def read_version(self, gcode):
        with open(gcode) as f:
            for ln in f:
                if ln.startswith("; generated by"):
                    self.version = ln[len("; generated by"):].strip()
                    return

    def summary(self, stdout):
        """Parses the one line `sx slice` prints: layers, ms, bytes, estimated seconds."""
        text = ""
        for path in (stdout, stdout + ".err"):
            try:
                text += open(path).read()
            except OSError:
                pass
        m = re.search(r"(\d+) layers, ([\d.]+) ms, (\d+) bytes of G-code, (\d+) s estimated", text)
        return {"estimated_time_s": int(m.group(4)), "in_process_ms": float(m.group(2))} if m else {}

    def bench_job(self, model, out_dir):
        """`sx bench` for one cold run, which splits slice, G-code and preview time."""
        cfg = os.path.join(out_dir, f"{model}-sx-bench.json")
        _write_json(cfg, {"name": model, "model": self.stl(model), "expect_layers": 0, "config": settings.sx_config()})
        out = os.path.join(out_dir, f"{model}-sx-bench.out")
        return Job([self.path, "bench", "--config", cfg, "--runs", "1", "--warmup", "0", "--no-shards", "--json"], None, stdout=out)


class Orca:
    name = "OrcaSlicer"
    key = "orca"

    def __init__(self, path=None):
        self.path = path or os.environ.get("ORCA_BIN") or _first_existing([
            "/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer", "~/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer",
            r"C:\Program Files\OrcaSlicer\orca-slicer.exe"]) or shutil.which("orca-slicer") or shutil.which("OrcaSlicer")
        self.version = None

    def available(self):
        return bool(self.path)

    def prepare(self, work, models):
        self.work = work
        flavor = "marlin2"
        machine = {"type": "machine", "name": "compare machine", "from": "User", "inherits": "MyMarlin 0.4 nozzle", **settings.slicer_machine(flavor)}
        process = {"type": "process", "name": "compare process", "from": "User", "inherits": "0.20mm Standard @MyMarlin",
                   "compatible_printers": ["compare machine", "MyMarlin 0.4 nozzle"], "compatible_printers_condition": "", **settings.slicer_process(flavor)}
        filament = {"type": "filament", "name": "compare filament", "from": "User", "inherits": "Generic PLA @System",
                    "compatible_printers": ["compare machine", "MyMarlin 0.4 nozzle"], "compatible_printers_condition": "", **settings.slicer_filament()}
        self.files = {}
        for n, d in (("machine", machine), ("process", process), ("filament", filament)):
            self.files[n] = os.path.join(work, f"orca-{n}.json")
            _write_json(self.files[n], d)
        self._read_version(models)

    def _read_version(self, models):
        log = os.path.join(self.work, "orca-version.log")
        out = os.path.join(self.work, "orca-version-out")
        os.makedirs(out, exist_ok=True)
        subprocess.run(self._cmd(models["cube"], out, ["--debug", "3", "--logfile", log]), capture_output=True)
        try:
            m = re.search(r"Current OrcaSlicer Version (\S+)", open(log).read())
            self.version = m.group(1) if m else "unknown"
        except OSError:
            self.version = "unknown"

    def _cmd(self, stl, out_dir, extra=()):
        return [self.path, "--slice", "0", "--outputdir", os.path.abspath(out_dir), *extra,
                "--load-settings", f"{self.files['machine']};{self.files['process']}", "--load-filaments", self.files["filament"], os.path.abspath(stl)]

    def job(self, model, out_dir, tag="run"):
        d = os.path.abspath(os.path.join(out_dir, f"{model}-orca"))
        shutil.rmtree(d, ignore_errors=True)
        os.makedirs(d)
        stl = os.path.join(self.work, "models", f"{model}.stl")
        return Job(self._cmd(stl, d, ["--debug", "1"]), os.path.join(d, "plate_1.gcode"))


class Bambu:
    name = "Bambu Studio"
    key = "bambu"
    MACHINE = "Bambu Lab P1S 0.4 nozzle"
    PROCESS = "0.20mm Standard @BBL X1C"
    FILAMENT = "Bambu PLA Basic @BBL P1S 0.4 nozzle"

    def __init__(self, path=None, profiles=None):
        self.path = path or os.environ.get("BAMBU_BIN") or _first_existing([
            "/Applications/BambuStudio.app/Contents/MacOS/BambuStudio", "~/Applications/BambuStudio.app/Contents/MacOS/BambuStudio",
            r"C:\Program Files\Bambu Studio\bambu-studio.exe"]) or shutil.which("bambu-studio") or shutil.which("BambuStudio")
        self.profiles = profiles or os.environ.get("BAMBU_PROFILES")
        self.version = None

    def available(self):
        return bool(self.path)

    def _find_profiles(self):
        if self.profiles:
            return self.profiles
        p = os.path.realpath(self.path)
        for _ in range(6):
            p = os.path.dirname(p)
            for rel in (("Resources", "profiles", "BBL"), ("resources", "profiles", "BBL")):
                cand = os.path.join(p, *rel)
                if os.path.isdir(cand):
                    return cand
        raise RuntimeError("Bambu Studio profile folder not found; pass --bambu-profiles .../profiles/BBL")

    def _resolve(self, kind, name):
        with open(os.path.join(self.profiles, kind, name + ".json")) as f:
            d = json.load(f)
        base = self._resolve(kind, d["inherits"]) if d.get("inherits") else {}
        skip = {"inherits", "name", "from", "instantiation", "setting_id", "type", "filament_id"}
        base.update({k: v for k, v in d.items() if k not in skip})
        return base

    @staticmethod
    def _read_stl(path):
        with open(path, "rb") as f:
            data = f.read()
        n = struct.unpack_from("<I", data, 80)[0]
        verts, index, tris = {}, [], []
        for rec in struct.iter_unpack("<12fH", memoryview(data)[84:84 + 50 * n]):
            for k in (3, 6, 9):
                v = rec[k:k + 3]
                i = verts.get(v)
                if i is None:
                    i = verts[v] = len(verts)
                index.append(i)
        return list(verts), index

    def _write_3mf(self, path, stl, project_settings, legacy_header):
        verts, idx = self._read_stl(stl)
        with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
            z.writestr("[Content_Types].xml", '<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
                       '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
                       '<Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/></Types>')
            z.writestr("_rels/.rels", '<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
                       '<Relationship Target="/3D/3dmodel.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>')
            with z.open("3D/3dmodel.model", "w", force_zip64=True) as m:
                head = '<?xml version="1.0" encoding="UTF-8"?>\n<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">\n'
                if legacy_header:
                    head += ' <metadata name="Application">BambuStudio-02.08.02.61</metadata>\n <metadata name="BambuStudio:3mfVersion">1</metadata>\n'
                m.write((head + ' <resources>\n  <object id="1" type="model">\n   <mesh>\n    <vertices>\n').encode())
                for i in range(0, len(verts), 20000):
                    m.write("".join(f'     <vertex x="{x:.6g}" y="{y:.6g}" z="{zz:.6g}"/>\n' for x, y, zz in verts[i:i + 20000]).encode())
                m.write(b"    </vertices>\n    <triangles>\n")
                for i in range(0, len(idx), 60000):
                    m.write("".join(f'     <triangle v1="{idx[j]}" v2="{idx[j + 1]}" v3="{idx[j + 2]}"/>\n' for j in range(i, min(i + 60000, len(idx)), 3)).encode())
                m.write(b'    </triangles>\n   </mesh>\n  </object>\n </resources>\n <build>\n  <item objectid="1" printable="1"/>\n </build>\n</model>\n')
            z.writestr("Metadata/project_settings.config", json.dumps(project_settings))

    def prepare(self, work, models):
        self.work = work
        self.profiles = self._find_profiles()
        # Step 1: ask Bambu Studio for its own default settings, through a project with only a printer name.
        seed = os.path.join(work, "bambu-seed.3mf")
        self._write_3mf(seed, models["cube"], {"printer_settings_id": self.MACHINE}, legacy_header=False)
        out = os.path.abspath(os.path.join(work, "bambu-seed-out"))
        os.makedirs(out, exist_ok=True)
        base_path = os.path.join(out, "defaults.json")
        r = subprocess.run([self.path, "--export-settings", base_path, "--outputdir", out, "--debug", "2", os.path.abspath(seed)], capture_output=True, text=True)
        m = re.search(r"Current BambuStudio Version (\S+)", r.stdout + r.stderr)
        self.version = m.group(1) if m else "unknown"
        with open(base_path) as f:
            cfg = json.load(f)
        # Step 2: layer the installed machine, process and filament presets, then the matched settings.
        for kind, name in (("machine", self.MACHINE), ("process", self.PROCESS), ("filament", self.FILAMENT)):
            cfg.update(self._resolve(kind, name))
        for src in (settings.slicer_process("marlin"), settings.slicer_machine("marlin"), settings.slicer_filament()):
            for k, v in src.items():
                settings.assign(cfg, k, v)
        cfg.update({
            # An older 3MF format version makes Bambu Studio treat the file as a legacy project and
            # create the default plate. The names below point it at system presets it knows.
            "version": "02.01.01.52", "from": "project", "name": "project_settings",
            "print_settings_id": self.PROCESS, "printer_settings_id": self.MACHINE, "filament_settings_id": [self.FILAMENT],
            "inherits_group": [self.PROCESS, "", ""],
        })
        if settings.MATCHED["printable_area"][2][0] != 256:
            cfg["bed_exclude_area"] = ["0x0"]  # the P1S exclusion zone does not apply to a larger bed
        self.project = cfg
        self.projects = {}
        for name, stl in models.items():
            path = os.path.join(work, f"bambu-{name}.3mf")
            self._write_3mf(path, stl, cfg, legacy_header=True)
            self.projects[name] = path

    def job(self, model, out_dir, tag="run", debug=1):
        d = os.path.abspath(os.path.join(out_dir, f"{model}-bambu"))
        shutil.rmtree(d, ignore_errors=True)
        os.makedirs(d)
        return Job([self.path, "--slice", "1", "--outputdir", d, "--debug", str(debug), os.path.abspath(self.projects[model])],
                   os.path.join(d, "plate_1.gcode"), stdout=os.path.join(out_dir, f"{model}-bambu-{tag}.log"))

    @staticmethod
    def phases(log, t_launch, wall_ms):
        """Splits one run into phases using the timestamps in the debug-4 log."""
        marks = {}
        stamp = re.compile(r"\[(\d{4}-\d\d-\d\d \d\d:\d\d:\d\d\.\d+)\]")
        want = (("read", "Will start to read model file"), ("proc", "start Print::process"),
                ("done", "Slicing process finished"), ("end", "record_exit_reson"))
        first = None
        with open(log, errors="replace") as f:
            for ln in f:
                m = stamp.match(ln)
                if not m:
                    continue
                t = datetime.datetime.strptime(m.group(1), "%Y-%m-%d %H:%M:%S.%f").timestamp()
                first = first or t
                for k, needle in want:
                    if k not in marks and needle in ln:
                        marks[k] = t
        if len(marks) < 4 or first is None:
            return None
        end = t_launch + wall_ms / 1000
        return {"startup_ms": (marks["read"] - t_launch) * 1000, "load_ms": (marks["proc"] - marks["read"]) * 1000,
                "slice_ms": (marks["done"] - marks["proc"]) * 1000, "gcode_ms": (marks["end"] - marks["done"]) * 1000,
                "exit_ms": (end - marks["end"]) * 1000}
