// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
// Renders SeedData as supabase/seed/*.sql for the local stack, one file per module.
import type { SeedData, SeedTable } from '../rows'

type Cell = string | number | boolean | null | readonly string[] | { readonly [k: string]: unknown }

function literal(v: Cell): string {
  if (v === null) return 'null'
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  if (typeof v === 'number') {
    if (!Number.isFinite(v)) throw new RangeError('non-finite number in seed')
    return String(v)
  }
  if (typeof v === 'string') return `'${v.replaceAll("'", "''")}'`
  if (Array.isArray(v)) return v.length === 0 ? "'{}'::text[]" : `array[${(v as readonly string[]).map((s) => literal(s)).join(', ')}]::text[]`
  return `'${JSON.stringify(v).replaceAll("'", "''")}'::jsonb`
}

function insert(table: string, rows: readonly Record<string, Cell>[], omit: readonly string[] = []): string {
  const first = rows[0]
  if (!first) return `-- ${table}: no rows\n`
  const cols = Object.keys(first).filter((c) => !omit.includes(c))
  const values = rows.map((r) => `  (${cols.map((c) => literal(r[c] ?? null)).join(', ')})`).join(',\n')
  return `insert into ${table} (${cols.join(', ')}) values\n${values};\n`
}

/** Store seed tables in foreign key order. */
const STORE_TABLES: SeedTable[] = [
  'creators',
  'creator_links',
  'follows',
  'listings',
  'listing_versions',
  'listing_files',
  'print_profiles',
  'creator_featured',
  'likes',
  'comments',
  'makes',
  'collections',
  'collection_items',
  'downloads',
  'audit_log',
]

/** Columns the database fills in itself. audit_log.id is an identity column, so the rows take ids 1..n in order. */
const OMIT: Partial<Record<SeedTable, string[]>> = { audit_log: ['id'] }

function header(module: string): string[] {
  return [
    // REUSE-IgnoreStart
    '-- SPDX-License-Identifier: Apache-2.0',
    // REUSE-IgnoreEnd
    '-- Copyright (C) 2026 The SlicerX contributors',
    `-- Seed for the ${module} module. Generated by packages/store (pnpm --filter @slicerx/store seed:write). Do not edit by hand.`,
    '-- Local stack only. Every creator and member is fictional.',
    '',
  ]
}

/** File name under supabase/seed/ to contents, one file per database module. */
export function renderSeedSql(seed: SeedData): Record<string, string> {
  const auth = header('auth')
  const zero = '00000000-0000-0000-0000-000000000000'
  const authUsers = seed.users.map((u) => ({
    instance_id: zero,
    id: u.id,
    aud: 'authenticated',
    role: 'authenticated',
    email: u.email,
    encrypted_password: '',
    email_confirmed_at: '2026-06-01T00:00:00Z',
    raw_app_meta_data: JSON.stringify({ provider: 'email', providers: ['email'] }),
    raw_user_meta_data: JSON.stringify({ handle: u.handle, display_name: u.display_name }),
    created_at: '2026-06-01T00:00:00Z',
    updated_at: '2026-06-01T00:00:00Z',
    confirmation_token: '',
    recovery_token: '',
    email_change_token_new: '',
    email_change: '',
    // GoTrue reads these as plain strings; NULL breaks its admin user listing.
    email_change_token_current: '',
    phone_change: '',
    phone_change_token: '',
    reauthentication_token: '',
  }))
  auth.push(insert('auth.users', authUsers))
  const identities = seed.users.map((u) => ({
    id: u.id,
    user_id: u.id,
    provider_id: u.id,
    provider: 'email',
    identity_data: JSON.stringify({ sub: u.id, email: u.email, email_verified: true }),
    last_sign_in_at: '2026-06-01T00:00:00Z',
    created_at: '2026-06-01T00:00:00Z',
    updated_at: '2026-06-01T00:00:00Z',
  }))
  auth.push(insert('auth.identities', identities))
  // The sign-up trigger makes a member profile per user, with the handle and
  // display name from the metadata above. Roles and bans are set here.
  auth.push('-- Roles and bans. The sign-up trigger created every profile as a member.')
  for (const p of seed.profiles) {
    if (p.role === 'member' && p.banned_at === null) continue
    const sets = [`role = ${literal(p.role)}`]
    if (p.banned_at !== null) sets.push(`banned_at = ${literal(p.banned_at)}`, `ban_reason = ${literal(p.ban_reason)}`)
    auth.push(`update public.profiles set ${sets.join(', ')} where id = ${literal(p.id)};`)
    if (p.banned_at !== null) auth.push(`update auth.users set banned_until = 'infinity' where id = ${literal(p.id)};`)
  }
  auth.push('')
  const out: Record<string, string> = { 'auth.sql': auth.join('\n') }

  const store = header('store')
  // The migration already inserted the one settings row, so this is an update.
  for (const m of seed.library_settings) {
    store.push(`update public.library_settings set moderation_mode = ${literal(m.moderation_mode)}, max_file_mb = ${m.max_file_mb}, allowed_formats = ${literal(m.allowed_formats)}, updated_at = now();\n`)
  }
  for (const t of STORE_TABLES) store.push(insert(`public.${t}`, seed[t] as unknown as Record<string, Cell>[], OMIT[t]))
  out['store.sql'] = store.join('\n')
  return out
}
