// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
// @slicerx/ui. See README.md for the public API.
// Styles: import "@slicerx/ui/styles.css" once per app (it pulls in tokens.css).

export { NOCTURNE, NOCTURNE_VARS, ROLE, BRAND, FONTS, FONTS_HREF, MOTION, readToken, prefersReducedMotion } from './tokens'
export type { NocturneColor } from './tokens'

export { ICON_PATHS, ICON_GROUPS, ICON_COUNT } from './icons/icon-paths'
export type { IconName } from './icons/icon-paths'
export { Icon, isIconName, iconsReady } from './icons/icon'
export type { IconProps } from './icons/icon'
export { Mark, Logo, MARK_PATH, MARK_CUTS, markRings, markCutFor } from './icons/mark'
export type { MarkCut } from './icons/mark'
export type { MarkProps, LogoProps } from './icons/mark'

export { Button, ButtonLink, LinkButton } from './components/button'
export type { ButtonProps, ButtonLinkProps, LinkButtonProps, ButtonVariant, ButtonSize } from './components/button'
export { MakerTile, MAKERS, makerSlugFor } from './components/maker-tile'
export type { MakerTileProps, MakerSlug } from './components/maker-tile'
export { Chip, Pill, Kbd, Eyebrow } from './components/chip'
export type { ChipProps, ChipTone, PillProps, PillState, KbdProps, EyebrowProps } from './components/chip'
export { Input, Textarea, Select, Field } from './components/input'
export type { InputProps, TextareaProps, SelectProps, FieldProps } from './components/input'
export { Seg, Switch, SwitchRow } from './components/seg'
export { Range } from './components/range'
export type { RangeProps } from './components/range'
export { ScrubNumber, VectorField, scrubFactor, spokenUnit } from './components/scrub'
export type { ScrubNumberProps, VectorFieldProps, Axis } from './components/scrub'
export type { SegProps, SegOption, SwitchProps, SwitchRowProps } from './components/seg'
export { Menu, MenuAnchor, MenuItem, MenuHeading, MenuSeparator } from './components/menu'
export type { MenuProps, MenuAnchorProps, MenuItemProps } from './components/menu'
export { EdgeTab, edgeChevron } from './components/edge-tab'
export type { EdgeTabProps, EdgeSide } from './components/edge-tab'
export { ContextMenu, MenuIcon, MenuIconRow, useContextMenu, isMenuKey, placeAt, pressStays, LONG_PRESS_MS, LONG_PRESS_SLOP } from './components/context-menu'
export type { ContextMenuProps, ContextMenuBind, MenuIconProps, MenuPoint } from './components/context-menu'
export { ResizeEdge } from './components/resize-edge'
export type { ResizeEdgeProps } from './components/resize-edge'
export { TooltipHost, tipAttrs, TIP_TIMING } from './components/tooltip'
export { Raven, RAVEN_BODY, RAVEN_WING, RAVEN_EYE } from './components/raven'
export { motionPreference, motionReduced, resolveMotion, setMotionPreference, subscribeMotion, systemReducesMotion } from './motion'
export { useMotionReduced } from './motion-hook'
export type { MotionPreference } from './motion'
export type { RavenProps } from './components/raven'
export type { TooltipHostProps, TipContent, TipSpec } from './components/tooltip'
export { Dialog } from './components/dialog'
export type { DialogProps } from './components/dialog'
export { CommandPalette } from './components/command-palette'
export type { CommandPaletteProps, PaletteGroup, PaletteItem } from './components/command-palette'
export { Panel, Block, KeyValues } from './components/panel'
export type { PanelProps, BlockProps, KeyValueProps } from './components/panel'
export { Rail } from './components/rail'
export type { RailProps, RailItem } from './components/rail'
export { AppBar, Tabs, SearchButton, Avatar, StatusLine, Frame, WORKSPACE_TABS } from './components/app-bar'
export type { AppBarProps, TabsProps, TabSpec, WorkspaceId, SearchButtonProps, AvatarProps, StatusLineProps, FrameProps } from './components/app-bar'
export { ToastProvider, useToast } from './components/toast'
export type { ToastTone, ToastOptions } from './components/toast'

export { SCENE_VARS, nocturne, createTheme, themeToVars, themeToCss, applyTheme, clearTheme, onThemeChange, resolveColor, THEME_EVENT } from './theme'
export type { Theme, ThemeInput, ThemeColors, ThemeGradient, ThemeFonts, ThemeRadius, ThemeSpacing, ThemeScene, ColorScheme } from './theme'
export { THEME_FILE_VERSION, TEXT_CONTRAST, GLYPH_CONTRAST, MAX_THEME_BYTES, derivePalette, deriveScene, SCENE_KEYS, themeColors, themeFromFile, validateThemeFile, parseThemeText, serializeTheme, themeWarnings, mixHex, contrast, readable, rehue } from './themefile'
export type { ThemeFile, DerivedPalette, ThemeResult } from './themefile'
export { BUNDLED_THEMES, DEFAULT_DARK_THEME, DEFAULT_LIGHT_THEME, DEFAULT_THEME_IDS, allThemes, findTheme, pickTheme, themeForScheme, slugify } from './theme-library'
export type { ThemeIds } from './theme-library'
export { UI_FONTS, MONO_FONTS, DEFAULT_UI_FONT, DEFAULT_MONO_FONT, THEME_FONT_CHOICE, resolveFonts } from './fonts'
export type { FontOption, FontChoice, ResolvedFonts } from './fonts'
export { nocturneLight, forge, themes } from './themes'
export type { ThemeName } from './themes'
export { ThemeProvider, useTheme } from './theme-provider'
export type { ThemeProviderProps, ThemeContextValue, IconOverrides } from './theme-provider'

export { useEdgeGlow } from './hooks/use-edge-glow'
export type { EdgeGlowOptions } from './hooks/use-edge-glow'
export { useDismiss } from './hooks/use-dismiss'
export * from './lookfeel'
