// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
// Byte vectors shared with the Rust port of the session protocol (sx-link, src/pair_session.rs).
// The test rebuilds every value from fixed randomness and checks it against vectors.json, so a
// change on either side shows up as a failure. UPDATE_VECTORS=1 rewrites the file.
import { readFileSync, writeFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { frame, toB64url, toHex, utf8 } from '../src/bytes'
import { dhKeyPair, kdf, mac, sasDigits, sign, type PairEnv } from '../src/crypto'
import { pairingRoutes } from '../src/offer'
import { acceptSession, macKey, openSession, type HostChannel } from '../src/session'
import { memoryPipePair } from '../src/transport'
import { testEnv } from './helpers'

const FILE = new URL('./vectors.json', import.meta.url)

/** An env that records every random byte string it hands out. */
function recording(seed: string): PairEnv & { drawn: string[] } {
  const env = testEnv(seed)
  const drawn: string[] = []
  return {
    now: env.now,
    drawn,
    random(n) {
      const b = env.random(n)
      drawn.push(toHex(b))
      return b
    },
  }
}

async function build() {
  const deviceKey = testEnv('vectors key').random(32)
  const hostDh = dhKeyPair(testEnv('vectors host static'))
  const device = recording('vectors device')
  const host = recording('vectors host')
  const [a, b] = memoryPipePair()
  const toDevice: string[] = []
  const toHost: string[] = []
  const host_: { ch: HostChannel | null } = { ch: null }
  let initText = ''
  let acceptText = ''
  b.onFrame((t) => {
    if (!host_.ch) {
      initText = t
      host_.ch = acceptSession(host, JSON.parse(t), deviceKey, hostDh.secretKey, (f) => {
        if (!acceptText) acceptText = f
        else toDevice.push(f)
        b.send(f)
      })
    } else {
      toHost.push(t)
      host_.ch.deliver(JSON.parse(t))
    }
  })
  const channel = await openSession(a, { env: device, deviceKey, hostDhPub: hostDh.publicKey, timeoutMs: 1000 })
  const fromDevice = ['{"id":1,"m":"printers"}', '{"id":2,"m":"status","p":{"printerId":"bay-4"}}']
  const fromHost = ['{"id":1,"r":[]}']
  const gotOnHost: unknown[] = []
  host_.ch?.onMessage((m: unknown) => gotOnHost.push(m))
  for (const m of fromDevice) channel.send(JSON.parse(m))
  for (const m of fromHost) host_.ch?.send(JSON.parse(m))
  await new Promise((r) => setTimeout(r, 10))
  expect(gotOnHost).toEqual(fromDevice.map((m) => JSON.parse(m)))

  const signSeed = testEnv('vectors sign').random(32)
  const routes = pairingRoutes(deviceKey)
  return {
    note: 'Generated by packages/pair/test/vectors.test.ts. Hex for raw bytes, frames as sent on the wire.',
    primitives: {
      frame: { parts: ['sx-pair/v1', 'label', 'bytes:00ff10'], hex: toHex(frame('sx-pair/v1', 'label', new Uint8Array([0, 255, 16]))) },
      kdf: { ikm: toHex(deviceKey), label: 'route host', length: 32, hex: toHex(kdf(deviceKey, undefined, 'route host')) },
      kdfSalted: { ikm: toHex(deviceKey), salt: '0102', label: 'session keys', length: 64, hex: toHex(kdf(deviceKey, new Uint8Array([1, 2]), 'session keys', 64)) },
      mac: { key: toHex(deviceKey), label: 'init', parts: ['a', 'b'], hex: toHex(mac(deviceKey, 'init', 'a', 'b')) },
      sas: { material: '0123456789', digits: sasDigits(new Uint8Array([1, 35, 69, 103, 137])) },
      sign: { seed: toHex(signSeed), label: 'decision', message: toHex(utf8('approve r-1')), sig: toHex(sign(signSeed, 'decision', utf8('approve r-1'))) },
    },
    session: {
      deviceKey: toHex(deviceKey),
      hostDhSecret: toHex(hostDh.secretKey),
      hostDhPub: toHex(hostDh.publicKey),
      macKey: toHex(macKey(deviceKey)),
      routes,
      deviceRandom: device.drawn,
      hostRandom: host.drawn,
      init: initText,
      accept: acceptText,
      fromDevice: fromDevice.map((plain, i) => ({ plain, frame: toHost[i] })),
      fromHost: fromHost.map((plain, i) => ({ plain, frame: toDevice[i] })),
    },
    b64url: { hex: '00010203fdfeff', text: toB64url(new Uint8Array([0, 1, 2, 3, 253, 254, 255])) },
  }
}

describe('shared vectors', () => {
  it('match vectors.json', async () => {
    const v = await build()
    if (process.env['UPDATE_VECTORS'] === '1') writeFileSync(FILE, `${JSON.stringify(v, null, 2)}\n`)
    expect(v).toEqual(JSON.parse(readFileSync(FILE, 'utf8')))
  })
})
