// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
// CPace against the draft's vectors, and the pairing exchange against vectors the Rust hub
// (packages/connect/cpace and sx-link) checks too. UPDATE_VECTORS=1 rewrites the shared file.
import assert from 'node:assert/strict'
import { readFileSync, writeFileSync } from 'node:fs'
import { test } from 'node:test'
import { createHash } from 'node:crypto'
import { generator, generatorString, iskIr, pakeAnswer, pakeStart, scalar, secret, share, type PakeContext } from './cpace.ts'

const hex = (s: string) => Uint8Array.from(Buffer.from(s.replace(/\s+/g, ''), 'hex'))
const toHex = (b: Uint8Array) => Buffer.from(b).toString('hex')
const enc = new TextEncoder()

test('CPace matches draft-irtf-cfrg-cpace-18 appendix B.3', () => {
  const ci = hex('6f630b425f726573706f6e6465720b415f696e69746961746f72')
  const sid = hex('7e4b4791d6a8ef019b936c79fb7f2c57')
  const gs = generatorString(enc.encode('Password'), ci, sid)
  assert.equal(gs.length, 172)
  const g = generator(enc.encode('Password'), ci, sid)
  assert.equal(toHex(g.toBytes()), 'a6fc82c3b8968fbb2e06fee81ca858586dea50d248f0c7ca6a18b0902a30b36b')
  const ya = scalar(hex('da3d23700a9e5699258aef94dc060dfda5ebb61f02a5ea77fad53f4ff0976d08'))
  const yb = scalar(hex('d2316b454718c35362d83d69df6320f38578ed5984651435e2949762d900b80d'))
  const a = share(ya, g)
  const b = share(yb, g)
  assert.equal(toHex(a), 'd40fb265a7abeaee7939d91a585fe59f7053f982c296ec413c624c669308f87a')
  assert.equal(toHex(b), '08bcf6e9777a9c313a3db6daa510f2d398403319c2341bd506a92e672eb7e307')
  const k = secret(ya, b)
  assert.ok(k)
  assert.equal(toHex(k), toHex(secret(yb, a) ?? new Uint8Array()))
  assert.equal(toHex(k), 'e22b1ef7788f661478f3cddd4c600774fc0f41e6b711569190ff88fa0e607e09')
  assert.equal(
    toHex(iskIr(sid, k, a, enc.encode('ADa'), b, enc.encode('ADb'))),
    '4c5469a16b2364c4b944ebc1a79e51d1674ad47db26e8718154f59faebfaa52d8346f30aa58377117eb20d527f2cbc5c76381f7fd372e89df8239f87f2e02ed1',
  )
  assert.equal(secret(ya, new Uint8Array(32)), null, 'the identity aborts')
  assert.equal(secret(ya, new Uint8Array(32).fill(0xff)), null, 'a non-encoding aborts')
})

/** Deterministic bytes for the shared vectors. */
const det = (label: string) => Uint8Array.from(createHash('sha256').update(label).digest())

function build() {
  const ctx: PakeContext = { hubKey: det('hub key'), port: 47615, clientNonce: det('client nonce'), hubNonce: det('hub nonce') }
  const codes = { app: 'ABCD-EFGH', agent: 'JKMN-PQRS', watch: 'TUVW-XYZ2' }
  const clientRandom = det('client y')
  const hubRandom = [det('hub y app'), det('hub y agent'), det('hub y watch')]
  const client = pakeStart('jkmn-pqrs', ctx, clientRandom)
  let i = 0
  const hub = pakeAnswer(codes, ctx, client.ya, () => hubRandom[i++] ?? new Uint8Array(32))
  assert.ok(hub)
  const tags = client.respond(hub.yb)
  assert.ok(tags)
  const ok = hub.check(tags)
  assert.equal(ok?.role, 'agent')
  assert.ok(ok && client.hubConfirmed(ok.confirm))
  return {
    note: 'Generated by packages/connect/link-client/src/cpace.test.ts. Hex for bytes. The client holds the agent code.',
    hubKey: toHex(ctx.hubKey),
    port: ctx.port,
    clientNonce: toHex(ctx.clientNonce),
    hubNonce: toHex(ctx.hubNonce),
    codes,
    clientCode: 'jkmn-pqrs',
    clientRandom: toHex(clientRandom),
    hubRandom: hubRandom.map(toHex),
    ya: toHex(client.ya),
    yb: { app: toHex(hub.yb.app ?? new Uint8Array()), agent: toHex(hub.yb.agent ?? new Uint8Array()), watch: toHex(hub.yb.watch ?? new Uint8Array()) },
    clientTags: { app: toHex(tags.app), agent: toHex(tags.agent), watch: toHex(tags.watch) },
    role: ok?.role,
    hubConfirm: toHex(ok?.confirm ?? new Uint8Array()),
  }
}

const FILE = new URL('../../cpace/vectors.json', import.meta.url)

test('the pairing exchange matches the vectors the Rust hub checks', () => {
  const v = build()
  if (process.env['UPDATE_VECTORS'] === '1') writeFileSync(FILE, `${JSON.stringify(v, null, 2)}\n`)
  assert.deepEqual(v, JSON.parse(readFileSync(FILE, 'utf8')))
})

test('a wrong code fails, and what the client sends cannot be checked offline', () => {
  const ctx: PakeContext = { hubKey: det('k'), port: 47615, clientNonce: det('n1'), hubNonce: det('n2') }
  // A program posing as the hub picks its own messages for a guessed code.
  const client = pakeStart('ABCD-EFGH', ctx, det('c'))
  let n = 0
  const fake = pakeAnswer({ app: 'ZZZZ-ZZZZ' }, ctx, client.ya, () => det(`f${n++}`))
  assert.ok(fake)
  // The client needs a message per role; give it the guessed one three times.
  const yb = { app: fake.yb.app, agent: fake.yb.app, watch: fake.yb.app }
  const tags = client.respond(yb)
  assert.ok(tags)
  // The guess was wrong: no tag verifies. Checking another guess against these tags would need the
  // client's secret scalar, which never leaves it, so each run is one online guess.
  assert.equal(fake.check(tags), null)
  assert.equal(client.hubConfirmed(new Uint8Array(32)), false)
  // The right code against a real hub works.
  let m = 0
  const real = pakeAnswer({ app: 'abcd efgh' }, ctx, client.ya, () => det(`r${m++}`))
  const t2 = client.respond({ app: real?.yb.app, agent: real?.yb.app, watch: real?.yb.app })
  assert.ok(t2)
  const ok = real?.check(t2)
  assert.equal(ok?.role, 'app')
  assert.ok(ok && client.hubConfirmed(ok.confirm))
})
