// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
// design/tokens.css and design/icons.js are generated copies. The sources are packages/ui/src/tokens.css and
// packages/ui/icons/*.mjs, plus design/brand-overrides.css (the approved brand ground and colors, kept for the brand pages) (through the generated packages/ui/src/icons/icon-paths.ts). Edit those, not these.
//   node design/sync.mjs           write both files
//   node design/sync.mjs --check   exit 1 when either file is out of date
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')
const { ICON_PATHS, ICON_GROUPS } = await import(pathToFileURL(resolve(root, 'packages/ui/src/icons/icon-paths.ts')).href)
const { SMALL_ICON_PATHS } = await import(pathToFileURL(resolve(root, 'packages/ui/src/icons/icon-small.ts')).href)
// a Windows checkout with core.autocrlf has CRLF in the working tree; generate and compare with LF
const read = (path) => readFileSync(path, 'utf8').replace(/\r\n/g, '\n')

const tokens =
  '/* SPDX-License-Identifier: Apache-2.0\n   Copyright (C) 2026 The SlicerX contributors */\n' +
  '/* Generated by design/sync.mjs from packages/ui/src/tokens.css. Do not edit. */\n' +
  read(resolve(root, 'packages/ui/src/tokens.css'))
    .replace(/^\/\* SPDX[^\n]*\n/, '')
    .replace(/^\/\* Copyright[^\n]*\n/, '') +
  '\n' +
  read(resolve(here, 'brand-overrides.css')).replace(/^\/\* SPDX[^*]*\*\/\n/, '')

const icons =
  '// SPDX-License-Identifier: Apache-2.0\n// Copyright (C) 2026 The SlicerX contributors\n' +
  '// Generated by design/sync.mjs from packages/ui/icons. Do not edit.\n' +
  '/* SlicerX icon set. 24px grid, 1.75 stroke, round caps and joins, currentColor. */\n' +
  `const SX_ICON_GROUPS = ${JSON.stringify(ICON_GROUPS, null, 2)};\n` +
  `const SX_ICONS = {\n${Object.entries(ICON_PATHS)
    .map(([n, d]) => `  ${JSON.stringify(n)}:${JSON.stringify(d)},`)
    .join('\n')}\n};\n` +
  '/* 16px versions of some of them, for 16px and smaller. 16px grid, 1.5 stroke. */\n' +
  `const SX_SMALL_ICONS = {\n${Object.entries(SMALL_ICON_PATHS)
    .map(([n, d]) => `  ${JSON.stringify(n)}:${JSON.stringify(d)},`)
    .join('\n')}\n};\n`

const files = [
  ['tokens.css', tokens],
  ['icons.js', icons],
]
if (process.argv.includes('--check')) {
  const stale = files.filter(([name, text]) => read(resolve(here, name)) !== text).map(([name]) => name)
  if (stale.length) {
    console.error(`${stale.join(', ')} out of date. Run node design/sync.mjs`)
    process.exit(1)
  }
} else for (const [name, text] of files) writeFileSync(resolve(here, name), text)
