/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright (C) 2026 The SlicerX contributors */
/* Generated by cbindgen from packages/core/ffi/src/lib.rs. Do not edit. */

#ifndef SLICERX_H
#define SLICERX_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/*
 ABI version; bumped on any breaking change to this header.
 */
#define SX_ABI_VERSION 1

/*
 A finished slice: result JSON, G-code and SXPV preview.
 */
typedef struct SxResult SxResult;

/*
 Bytes owned by the library. Free with `sx_buffer_free`.
 */
typedef struct {
  uint8_t *ptr;
  size_t len;
} SxBuffer;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 The ABI version this library implements (`SX_ABI_VERSION`).
 */
uint32_t sx_abi_version(void);

/*
 Loads a model from `len` bytes at `data`; `file_name` (UTF-8, may be NULL)
 picks the format by extension. Returns a mesh id, or 0 on error.

 # Safety

 `data` must point to `len` readable bytes, and `file_name` must be NULL or
 a NUL-terminated string.
 */
uint64_t sx_mesh_load(const uint8_t *data, size_t len, const char *file_name);

/*
 Forgets a mesh. Results that used it stay valid.
 */
void sx_mesh_free(uint64_t mesh);

/*
 Slices a `SliceRequest` JSON (`sx schema request`). Object `mesh` values
 are ids from `sx_mesh_load`, as numbers or strings. Returns a result
 handle, or NULL on error.

 # Safety

 `request_json` must be a NUL-terminated UTF-8 string.
 */
SxResult *sx_slice(const char *request_json);

/*
 The result JSON (`sx schema result`), UTF-8, not NUL-terminated.

 # Safety

 `result` must be NULL or a live handle from `sx_slice`.
 */
SxBuffer sx_result_json(const SxResult *result);

/*
 The G-code.

 # Safety

 `result` must be NULL or a live handle from `sx_slice`.
 */
SxBuffer sx_result_gcode(const SxResult *result);

/*
 The SXPV preview buffers.

 # Safety

 `result` must be NULL or a live handle from `sx_slice`.
 */
SxBuffer sx_result_preview(const SxResult *result);

/*
 Frees a buffer returned by this library. NULL buffers are ignored.

 # Safety

 `buffer` must come from this library and not be freed before.
 */
void sx_buffer_free(SxBuffer buffer);

/*
 Frees a result. NULL is ignored.

 # Safety

 `result` must be NULL or a handle from `sx_slice` not freed before.
 */
void sx_result_free(SxResult *result);

/*
 The last error on this thread, or NULL. Valid until the next call into
 the library on the same thread.
 */
const char *sx_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SLICERX_H */
