// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
// A single pass G-code reader: layers, temperatures, feed rates, retraction,
// fan, volumetric flow and time by feature. It walks the text line by line
// with indexOf, keeps only counters and small histograms, and never builds a
// list of moves, so large files stay fast. File text is untrusted: only
// numbers and short labels come out of it.

export interface GcodeStats {
  lines: number
  moves: number
  layers: number
  maxZMm: number
  /** Distinct set temperatures in order of appearance, C. `nozzlePrinting` holds only the nozzle temperatures that
   * extruding moves ran at, so start G-code steps such as a probing or wipe temperature are left out of it. */
  temps: { nozzle: number[]; bed: number[]; chamber: number[]; nozzlePrinting: number[] }
  feed: { maxPrintMmS: number; typicalPrintMmS: number; maxTravelMmS: number }
  retractions: { count: number; totalMm: number; typicalMm: number; firmware: number }
  fan: { maxPct: number; changes: number }
  extrusion: { relative: boolean; filamentMm: number; filamentDiameterMm: number }
  flow: { peakMm3s: number; p95Mm3s: number }
  /** The filament profile's max volumetric speed, mm3/s, from an Orca or Bambu Studio config comment; the largest
   * when the file has several filaments. The slicer held every move to it. */
  profileMaxFlowMm3s: number | null
  /** Estimated from move lengths and feed rates, no acceleration; rough. */
  movesTimeS: number
  /** The slicer's own estimate from a header comment, when present. */
  slicerTimeS: number | null
  timeByFeature: { feature: string; s: number; pct: number }[]
  /** Short label from a "generated by" comment, cut to 60 characters. */
  generator: string | null
}

/** "1d 2h 3m 4s", "2h 05m", "12m 3s" to seconds. Null when nothing parses. */
export function parseDuration(s: string): number | null {
  let total = 0
  let hit = false
  for (const m of s.matchAll(/(\d+(?:\.\d+)?)\s*([dhms])/gi)) {
    const v = Number(m[1])
    const u = (m[2] ?? '').toLowerCase()
    total += u === 'd' ? v * 86400 : u === 'h' ? v * 3600 : u === 'm' ? v * 60 : v
    hit = true
  }
  return hit ? Math.round(total) : null
}

/** Weighted quantile from a histogram of value / bin (rounded) -> weight. */
function quantile(hist: Map<number, number>, q: number, bin: number): number {
  const entries = [...hist.entries()].sort((a, b) => a[0] - b[0])
  const total = entries.reduce((s, [, w]) => s + w, 0)
  if (total <= 0) return 0
  let acc = 0
  for (const [k, w] of entries) {
    acc += w
    if (acc >= q * total - 1e-9) return Math.round(k * bin * 10) / 10
  }
  return Math.round((entries[entries.length - 1]?.[0] ?? 0) * bin * 10) / 10
}

const FEATURE_NAMES: Record<string, string> = {
  'outer wall': 'outer wall',
  'external perimeter': 'outer wall',
  'wall-outer': 'outer wall',
  perimeter: 'inner wall',
  'inner wall': 'inner wall',
  'wall-inner': 'inner wall',
  'sparse infill': 'sparse infill',
  'internal infill': 'sparse infill',
  fill: 'sparse infill',
  'internal solid infill': 'solid infill',
  'solid infill': 'solid infill',
  skin: 'solid infill',
  'top surface': 'top surface',
  'top solid infill': 'top surface',
  'bottom surface': 'bottom surface',
  bridge: 'bridge',
  'bridge infill': 'bridge',
  'overhang wall': 'overhang wall',
  'overhang perimeter': 'overhang wall',
  support: 'support',
  'support material': 'support',
  'support interface': 'support interface',
  'support material interface': 'support interface',
  'gap infill': 'gap infill',
  skirt: 'skirt and brim',
  brim: 'skirt and brim',
  'skirt/brim': 'skirt and brim',
  'prime tower': 'prime tower',
  'wipe tower': 'prime tower',
  custom: 'custom',
}

function featureName(raw: string): string {
  const k = raw.trim().toLowerCase().replaceAll('_', ' ')
  return FEATURE_NAMES[k] ?? (k.replace(/[^a-z0-9 /-]/g, '').slice(0, 24) || 'other')
}

/**
 * Length of a G2 (clockwise) or G3 arc from (x0, y0) to (x1, y1), from its center offset I J or its radius R,
 * with dz as a helix and P as extra full circles. The chord alone undercounts a tight arc several times over,
 * which inflates its flow. Falls back to the chord when the arc is not well formed.
 */
export function arcLength(x0: number, y0: number, x1: number, y1: number, dz: number, cw: boolean, p: Map<string, number>): number {
  const chord = Math.hypot(x1 - x0, y1 - y0)
  let r: number
  let sweep: number
  const radius = p.get('R')
  if (p.has('I') || p.has('J')) {
    const cx = x0 + (p.get('I') ?? 0)
    const cy = y0 + (p.get('J') ?? 0)
    r = Math.hypot(x0 - cx, y0 - cy)
    sweep = Math.atan2(y1 - cy, x1 - cx) - Math.atan2(y0 - cy, x0 - cx)
    if (cw) sweep = sweep >= -1e-9 ? sweep - 2 * Math.PI : sweep
    else sweep = sweep <= 1e-9 ? sweep + 2 * Math.PI : sweep
    sweep = Math.abs(sweep)
  } else if (radius !== undefined && radius !== 0 && chord > 0) {
    r = Math.abs(radius)
    const half = Math.asin(Math.min(1, chord / (2 * r)))
    // A negative R takes the long way round.
    sweep = radius < 0 ? 2 * Math.PI - 2 * half : 2 * half
  } else return Math.hypot(chord, dz)
  if (!Number.isFinite(r) || r < 1e-9) return Math.hypot(chord, dz)
  // Marlin's P adds that many full circles.
  sweep += 2 * Math.PI * Math.max(0, Math.round(p.get('P') ?? 0))
  return Math.hypot(r * sweep, dz)
}

/**
 * Reads G-code text in one pass. Understands G0 to G3 (arcs by chord length),
 * G90/G91, M82/M83, G92, G10/G11, M104/M109, M140/M190, M141/M191, M106/M107
 * and the usual Orca, Prusa, Bambu and Cura comments for layers, features,
 * time and filament diameter.
 */
export function parseGcode(text: string): GcodeStats {
  let absXYZ = true
  let relE = false
  let x = 0, y = 0, z = 0, e = 0
  let feed = 1500 / 60
  let lines = 0
  let moves = 0
  let layerComments = 0
  let lastLayerZ = -Infinity
  let zLayers = 0
  let maxZ = 0
  let filamentMm = 0
  let diameter = 1.75
  let maxPrint = 0
  let maxTravel = 0
  let movesTime = 0
  let slicerTime: number | null = null
  let feature = 'other'
  let retractCount = 0
  let retractTotal = 0
  let retracting = false
  let cycle = 0
  let firmware = 0
  let fanMax = 0
  let fanChanges = 0
  let lastFan = -1
  let peakFlow = 0
  let generator: string | null = null
  let profileMaxFlow: number | null = null
  const nozzle: number[] = []
  const nozzlePrinting: number[] = []
  // The set temperature of each tool and the active tool, for nozzlePrinting.
  const toolTemp = new Map<number, number>()
  let tool = 0
  const bed: number[] = []
  const chamber: number[] = []
  const feedHist = new Map<number, number>()
  const flowHist = new Map<number, number>()
  const retractHist = new Map<number, number>()
  const featTime = new Map<string, number>()
  const closeCycle = (): void => {
    const rb = Math.round(cycle * 10)
    retractHist.set(rb, (retractHist.get(rb) ?? 0) + 1)
    retracting = false
  }
  const addTemp = (list: number[], v: number): void => {
    if (v > 0 && !list.includes(v) && list.length < 12) list.push(v)
  }
  const params = (code: string): Map<string, number> => {
    const out = new Map<string, number>()
    let i = 0
    const n = code.length
    while (i < n) {
      const c = code.charCodeAt(i)
      if (c >= 65 && c <= 90) {
        let j = i + 1
        while (j < n && code.charCodeAt(j) === 32) j++
        let k = j
        while (k < n) {
          const d = code.charCodeAt(k)
          if ((d >= 48 && d <= 57) || d === 46 || d === 45 || d === 43) k++
          else break
        }
        if (k > j) {
          const v = Number(code.slice(j, k))
          if (Number.isFinite(v)) out.set(code[i] ?? '', v)
        }
        i = k > j ? k : i + 1
      } else i++
    }
    return out
  }

  let pos = 0
  const len = text.length
  while (pos < len) {
    let end = text.indexOf('\n', pos)
    if (end < 0) end = len
    const raw = text.slice(pos, end)
    pos = end + 1
    lines++
    const semi = raw.indexOf(';')
    if (semi >= 0) {
      const comment = raw.slice(semi + 1).trim()
      if (comment) {
        const lc = comment.toLowerCase()
        if (lc.startsWith('type:') || lc.startsWith('feature:')) feature = featureName(comment.slice(comment.indexOf(':') + 1))
        else if (lc === 'layer_change' || lc === 'change_layer' || lc.startsWith('layer:')) layerComments++
        else if (slicerTime === null && (lc.startsWith('estimated printing time') || lc.includes('total estimated time'))) {
          const at = lc.includes('total estimated time') ? comment.slice(lc.indexOf('total estimated time') + 20) : comment.slice(comment.indexOf('=') + 1)
          slicerTime = parseDuration(at)
        } else if (slicerTime === null && lc.startsWith('time:')) {
          const v = Number(comment.slice(5))
          if (Number.isFinite(v)) slicerTime = Math.round(v)
        } else if (lc.startsWith('filament_diameter') || lc.startsWith('filament diameter')) {
          const v = Number.parseFloat(comment.slice(comment.search(/[=:]/) + 1))
          if (Number.isFinite(v) && v > 0.5 && v < 4) diameter = v
        } else if (lc.startsWith('filament_max_volumetric_speed')) {
          const vs = comment.slice(comment.indexOf('=') + 1).split(/[,;]/).map(Number.parseFloat).filter((v) => Number.isFinite(v) && v > 0)
          if (vs.length) profileMaxFlow = Math.max(...vs)
        } else if (generator === null && /^generated (by|with)/.test(lc)) {
          generator = comment.replace(/[^\w .,()+-]/g, '').slice(0, 60)
        }
      }
    }
    const code = (semi >= 0 ? raw.slice(0, semi) : raw).trim().toUpperCase()
    if (!code) continue
    const sp = code.search(/[\s]|(?<=\d)(?=[A-Z])/)
    const cmd = sp < 0 ? code : code.slice(0, sp)
    switch (cmd) {
      case 'G0':
      case 'G1':
      case 'G2':
      case 'G3': {
        const p = params(code.slice(cmd.length))
        const f = p.get('F')
        if (f !== undefined && f > 0) feed = f / 60
        const nx = p.has('X') ? (absXYZ ? (p.get('X') ?? 0) : x + (p.get('X') ?? 0)) : x
        const ny = p.has('Y') ? (absXYZ ? (p.get('Y') ?? 0) : y + (p.get('Y') ?? 0)) : y
        const nz = p.has('Z') ? (absXYZ ? (p.get('Z') ?? 0) : z + (p.get('Z') ?? 0)) : z
        let de = 0
        if (p.has('E')) {
          const ev = p.get('E') ?? 0
          de = relE ? ev : ev - e
          e = relE ? e + ev : ev
        }
        const dist = cmd === 'G2' || cmd === 'G3' ? arcLength(x, y, nx, ny, nz - z, cmd === 'G2', p) : Math.hypot(nx - x, ny - y, nz - z)
        const moved = dist > 1e-9
        if (moved || de !== 0) moves++
        const t = moved ? dist / feed : de !== 0 ? Math.abs(de) / feed : 0
        movesTime += t
        if (de > 1e-6 && retracting) closeCycle()
        if (de > 1e-6 && moved) {
          const set = toolTemp.get(tool)
          if (set !== undefined) addTemp(nozzlePrinting, set)
          filamentMm += de
          featTime.set(feature, (featTime.get(feature) ?? 0) + t)
          if (feed > maxPrint) maxPrint = feed
          const fb = Math.round(feed)
          feedHist.set(fb, (feedHist.get(fb) ?? 0) + dist)
          const flow = (de * Math.PI * (diameter / 2) ** 2) / t
          if (Number.isFinite(flow)) {
            if (flow > peakFlow && dist > 0.5) peakFlow = flow
            const qb = Math.round(flow * 10)
            flowHist.set(qb, (flowHist.get(qb) ?? 0) + t)
          }
          if (nz > lastLayerZ + 1e-6) {
            lastLayerZ = nz
            zLayers++
          }
          if (nz > maxZ) maxZ = nz
        } else if (de < -1e-6) {
          // Wipes spread one retraction over several moves; count the cycle once.
          if (!retracting) {
            retractCount++
            retracting = true
            cycle = 0
          }
          cycle += -de
          retractTotal += -de
          featTime.set(feature, (featTime.get(feature) ?? 0) + t)
        } else if (moved) {
          if (feed > maxTravel && de === 0) maxTravel = feed
          featTime.set('travel', (featTime.get('travel') ?? 0) + t)
        }
        x = nx
        y = ny
        z = nz
        break
      }
      case 'G90':
        absXYZ = true
        break
      case 'G91':
        absXYZ = false
        break
      case 'M82':
        relE = false
        break
      case 'M83':
        relE = true
        break
      case 'G92': {
        const p = params(code.slice(3))
        if (p.has('E')) e = p.get('E') ?? 0
        if (p.has('X')) x = p.get('X') ?? x
        if (p.has('Y')) y = p.get('Y') ?? y
        if (p.has('Z')) z = p.get('Z') ?? z
        break
      }
      case 'G10':
        if (!/[PLR]/.test(code.slice(3))) {
          retractCount++
          firmware++
        }
        break
      case 'M104':
      case 'M109': {
        const p = params(code.slice(4))
        const v = p.get('S') ?? p.get('R') ?? 0
        addTemp(nozzle, v)
        toolTemp.set(p.get('T') ?? tool, v)
        break
      }
      case 'M140':
      case 'M190':
        addTemp(bed, params(code.slice(4)).get('S') ?? params(code.slice(4)).get('R') ?? 0)
        break
      case 'M141':
      case 'M191':
        addTemp(chamber, params(code.slice(4)).get('S') ?? 0)
        break
      case 'M106': {
        const p = params(code.slice(4))
        const port = p.get('P')
        if (port === undefined || port === 0 || port === 1) {
          const pct = Math.round(((p.get('S') ?? 255) / 255) * 100)
          if (pct !== lastFan) fanChanges++
          lastFan = pct
          if (pct > fanMax) fanMax = pct
        }
        break
      }
      case 'M107':
        if (lastFan !== 0) fanChanges++
        lastFan = 0
        break
      default:
        if (/^T\d+$/.test(cmd)) tool = Number(cmd.slice(1))
        break
    }
  }
  if (retracting) closeCycle()
  const totalFeat = [...featTime.values()].reduce((a, b) => a + b, 0)
  const timeByFeature = [...featTime.entries()]
    .filter(([, s]) => s > 0.5)
    .sort((a, b) => b[1] - a[1])
    .map(([f, s]) => ({ feature: f, s: Math.round(s), pct: totalFeat ? Math.round((s / totalFeat) * 1000) / 10 : 0 }))
  const typicalRetract = [...retractHist.entries()].sort((a, b) => b[1] - a[1])[0]?.[0]
  return {
    lines,
    moves,
    layers: layerComments > 0 ? layerComments : zLayers,
    maxZMm: Math.round(maxZ * 100) / 100,
    temps: { nozzle, bed, chamber, nozzlePrinting },
    feed: { maxPrintMmS: Math.round(maxPrint), typicalPrintMmS: quantile(feedHist, 0.5, 1), maxTravelMmS: Math.round(maxTravel) },
    retractions: { count: retractCount, totalMm: Math.round(retractTotal * 10) / 10, typicalMm: typicalRetract === undefined ? 0 : typicalRetract / 10, firmware },
    fan: { maxPct: fanMax, changes: fanChanges },
    extrusion: { relative: relE, filamentMm: Math.round(filamentMm), filamentDiameterMm: diameter },
    flow: { peakMm3s: Math.round(peakFlow * 10) / 10, p95Mm3s: quantile(flowHist, 0.95, 0.1) },
    profileMaxFlowMm3s: profileMaxFlow,
    movesTimeS: Math.round(movesTime),
    slicerTimeS: slicerTime,
    timeByFeature,
    generator,
  }
}

export interface GcodeDiffRow {
  metric: string
  a: string
  b: string
  /** Why the difference matters, when it does. */
  matters?: string
}

const pctDiff = (a: number, b: number): number => (a === 0 ? (b === 0 ? 0 : 100) : Math.round(((b - a) / a) * 100))

/** Side by side rows for two files, with a reason on the rows whose difference matters. */
export function diffGcode(a: GcodeStats, b: GcodeStats): GcodeDiffRow[] {
  const rows: GcodeDiffRow[] = []
  const time = (s: GcodeStats): number => s.slicerTimeS ?? s.movesTimeS
  const add = (metric: string, av: string, bv: string, matters?: string | false): void => {
    const r: GcodeDiffRow = { metric, a: av, b: bv }
    if (matters) r.matters = matters
    rows.push(r)
  }
  const dt = pctDiff(time(a), time(b))
  add('time', `${Math.round(time(a) / 60)} min`, `${Math.round(time(b) / 60)} min`, Math.abs(dt) >= 10 && `B is ${Math.abs(dt)}% ${dt < 0 ? 'faster' : 'slower'}`)
  const dl = pctDiff(a.layers, b.layers)
  add('layers', String(a.layers), String(b.layers), Math.abs(dl) >= 10 && a.maxZMm > 0 && `about ${a.layers ? Math.round((a.maxZMm / a.layers) * 100) / 100 : '?'} mm vs ${b.layers ? Math.round((b.maxZMm / b.layers) * 100) / 100 : '?'} mm layers`)
  const df = pctDiff(a.feed.typicalPrintMmS, b.feed.typicalPrintMmS)
  add('typical print speed', `${a.feed.typicalPrintMmS} mm/s`, `${b.feed.typicalPrintMmS} mm/s`, Math.abs(df) >= 15 && `B prints ${Math.abs(df)}% ${df > 0 ? 'faster' : 'slower'}`)
  add('max print speed', `${a.feed.maxPrintMmS} mm/s`, `${b.feed.maxPrintMmS} mm/s`)
  const dq = pctDiff(a.flow.peakMm3s, b.flow.peakMm3s)
  add('peak flow', `${a.flow.peakMm3s} mm3/s`, `${b.flow.peakMm3s} mm3/s`, Math.abs(dq) >= 20 && 'higher flow needs a hotter nozzle and more cooling')
  const dfil = pctDiff(a.extrusion.filamentMm, b.extrusion.filamentMm)
  add('filament', `${(a.extrusion.filamentMm / 1000).toFixed(2)} m`, `${(b.extrusion.filamentMm / 1000).toFixed(2)} m`, Math.abs(dfil) >= 10 && `B uses ${Math.abs(dfil)}% ${dfil < 0 ? 'less' : 'more'} filament: fewer walls or less infill`)
  const ta = a.temps.nozzle.join('/') || 'none'
  const tb = b.temps.nozzle.join('/') || 'none'
  add('nozzle temps', `${ta} C`, `${tb} C`, ta !== tb && 'different nozzle temperature')
  add('bed temps', `${a.temps.bed.join('/') || 'none'} C`, `${b.temps.bed.join('/') || 'none'} C`, a.temps.bed.join('/') !== b.temps.bed.join('/') && 'different bed temperature')
  add('retractions', `${a.retractions.count} x ${a.retractions.typicalMm} mm`, `${b.retractions.count} x ${b.retractions.typicalMm} mm`, Math.abs(a.retractions.typicalMm - b.retractions.typicalMm) >= 0.2 && 'different retraction length')
  add('fan max', `${a.fan.maxPct}%`, `${b.fan.maxPct}%`, Math.abs(a.fan.maxPct - b.fan.maxPct) >= 20 && 'different part cooling')
  const fa = new Map(a.timeByFeature.map((f) => [f.feature, f.s]))
  const fb = new Map(b.timeByFeature.map((f) => [f.feature, f.s]))
  for (const f of new Set([...fa.keys(), ...fb.keys()])) {
    const av = fa.get(f) ?? 0
    const bv = fb.get(f) ?? 0
    if (Math.max(av, bv) < 60) continue
    const d = bv - av
    add(`time: ${f}`, `${Math.round(av / 60)} min`, `${Math.round(bv / 60)} min`, Math.abs(d) >= Math.max(120, 0.1 * (time(a) || 1)) && `${f} takes ${Math.round(Math.abs(d) / 60)} min ${d < 0 ? 'less' : 'more'} in B`)
  }
  return rows
}
