// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
// @slicerx/pilot. See README.md for the public API.
export { createPilot, type CreatePilotOptions, type PilotHost } from './runtime'
export { ASSISTANT_NAME } from './name'
export { HUGINN, MODEL_AUTOMATIC, MODEL_AUTOMATIC_LABEL, modelFor, MUNINN, tierForPrompt, type Tier } from './models'
export { defineSkill, defineTool, toolSpec, type AgentWork, type ApprovalPlan, type PilotTool, type ToolContext, type ToolHost, type ToolOutput } from './tool'
export { decide, normalizePolicy } from './gate'
export { createApprovalBroker, TOKEN_TTL_MS, type ApprovalBroker } from './permit/broker'
export { createKnowledgeBase, EMPTY_KB_INDEX, type KbIndex, type KnowledgeBase } from './kb/kb'
export { createKbPlanner } from './kb/planner'
export { createCombinedPlanner } from './kb/combined-planner'
export { parseIntent, type Intent } from './intent'
export type { PilotProject, ProjectObject, ProjectPlate } from './project'
export type { PlanResult, PlannedChange, SettingsPlanner } from './planner'
export { createAnthropicAdapter } from './provider/anthropic'
export { createOpenAiAdapter } from './provider/openai'
export { createOpenAiCompatibleAdapter } from './provider/openai-compatible'
export { createTransportClient } from './provider/client'
export { createScriptedClient, type ScriptStep } from './provider/scripted'
export type { LlmClient, LlmEvent, LlmMessage, LlmRequest } from './provider/types'
export { parsePilotConfig, DEFAULT_CONFIG } from './config'
export { createMemorySessionStore } from './session'
export { SKILL_INFO, SKILL_NAMES } from '../skills/index'
export { builtinTools } from './tools/index'
export { kbTools } from './tools/kb'
export { pluginToolsFrom } from './tools/plugins'
export { createShared, type ToolShared } from './shared'
export { createMemoryProject, rotatedBox, rotationMatrix, type MemoryObject, type MemoryProject, type MemoryProjectOptions } from './memory-project'
export { buildApprovalRequest, toolMessage } from './runtime'
export { createDemoClient } from './demo'
export type { GeomHost, HistoryHost, JobRecord, ModelHit, ModelSearchHost, ProfileSummary, ProfilesHost, ProjectExportHost, ProjectExportSlot, SetupAddInput, SetupConnection, SetupDiscovered, SetupHost, SetupProfileHit, SetupTestResult, ShareHost } from './hosts'
