// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
import { describe, expect, it } from 'vitest'
import { FEATURE, SXPV_EXTRA_FLAG, type FileRef, type Host } from '@slicerx/contracts'
import { currentSegment, indexLines, layerOfSegment, lineOfSegment, lineText, scroller, segmentOfLine, slidersFor } from '../src/workspaces/preview/gcode-lines'
import { featureOf, parseGcodePreview, scanMarks } from '../src/workspaces/preview/gcode-parse'
import { gcodeView } from '../src/workspaces/preview/gcode-file'
import { positionsOf } from '../src/workspaces/preview/marker-data'
import { closeFile, openGcodeFile } from '../src/workspaces/preview/gcode-source'
import { appStore, get, set } from '../src/state/store'

const enc = new TextEncoder()
const noWait = () => Promise.resolve()

/** Two layers of a 10 mm square with a wipe, a tool change, an arc and a pause, the way OrcaSlicer writes them. */
const SAMPLE = [
  '; generated by test',
  '; filament_diameter = 1.75',
  'G90',
  'M83',
  'M104 S215',
  'M106 S255',
  ';LAYER_CHANGE',
  'G1 Z0.2 F600',
  ';TYPE:Outer wall',
  ';WIDTH:0.45',
  ';HEIGHT:0.2',
  'G1 X0 Y0 F6000',
  'G1 X10 Y0 E0.5 F1800',
  'G1 X10 Y10 E0.5',
  'G1 E-0.8 F2400',
  ';WIPE_START',
  'G1 X8 Y10 E-0.1',
  ';WIPE_END',
  'T1',
  ';TYPE:Sparse infill',
  'G1 X0 Y10 F6000',
  'G1 X0 Y0 E0.5 F3000',
  'M601',
  ';LAYER_CHANGE',
  'G1 Z0.4',
  ';TYPE:Inner wall',
  'G1 X0 Y0',
  'G1 X10 Y0 E0.5 F1200',
  'G3 X10 Y10 I0 J5 E0.8',
  'M600',
  'PAUSE ; host pause',
  'G1 X0 Y10 E0.5',
  '',
].join('\n')

describe('G-code line index', () => {
  it('finds every line, with or without a final line break, in slices', async () => {
    const ix = await indexLines(enc.encode('G1 X1\nG1 X2\r\n;end'), { sliceBytes: 4, pause: noWait })
    expect(ix.count).toBe(3)
    expect([1, 2, 3].map((n) => lineText(ix, n))).toEqual(['G1 X1', 'G1 X2', ';end'])
    expect(lineText(ix, 0)).toBe('')
    expect(lineText(ix, 4)).toBe('')
    const trailing = await indexLines(enc.encode('a\nb\n'), { pause: noWait })
    expect(trailing.count).toBe(2)
    expect((await indexLines(new Uint8Array(0), { pause: noWait })).count).toBe(0)
  })

  it('stops when asked', async () => {
    const stop = new AbortController()
    stop.abort()
    await expect(indexLines(enc.encode('a\n'.repeat(100)), { sliceBytes: 8, signal: stop.signal, pause: noWait })).rejects.toThrow('Stopped')
  })

  it('keeps a 50 MB file responsive: no slice of work holds the page long', async () => {
    const line = 'G1 X123.456 Y78.901 E0.03456 ;comment\nG1 X12.3 Y7.8 E0.012\n'
    const repeats = Math.ceil((50 << 20) / line.length)
    const bytes = enc.encode(line.repeat(repeats))
    // The work between two yields is bounded by its size, which does not depend on how busy the machine is:
    // at most 4 MB of text to index and 150,000 lines to parse, a few ms each. Wall time is printed for the record.
    let pauses = 0
    let last = performance.now()
    let worst = 0
    const pause = async () => {
      pauses++
      worst = Math.max(worst, performance.now() - last)
      await Promise.resolve()
      last = performance.now()
    }
    const t0 = performance.now()
    const ix = await indexLines(bytes, { pause })
    const indexMs = performance.now() - t0
    expect(ix.count).toBe(repeats * 2)
    expect(lineText(ix, ix.count)).toBe('G1 X12.3 Y7.8 E0.012')
    expect(pauses).toBeGreaterThanOrEqual(Math.ceil(bytes.length / (4 << 20)) - 1)
    pauses = 0
    last = performance.now()
    const t1 = performance.now()
    const parsed = await parseGcodePreview(ix, { pause })
    const parseMs = performance.now() - t1
    expect(parsed.preview.segmentCount).toBeGreaterThan(0)
    expect(pauses).toBeGreaterThanOrEqual(Math.floor(ix.count / 150_000))
    console.info(`50 MB: index ${indexMs.toFixed(0)} ms, parse ${parseMs.toFixed(0)} ms, longest slice ${worst.toFixed(1)} ms`)
  })
})

describe('virtual scrolling', () => {
  it('maps lines to offsets and back at real height', () => {
    const sc = scroller(1000, 18)
    expect(sc.spacerPx).toBe(18000)
    expect(sc.scrollFor(101, 360)).toBe(1800)
    expect(sc.lineAt(1800, 360)).toBe(101)
  })
  it('scales a list past the element height limit and still reaches both ends', () => {
    const sc = scroller(3_000_000, 18, 1_000_000)
    expect(sc.spacerPx).toBe(1_000_000)
    expect(sc.lineAt(0, 400)).toBe(1)
    const end = sc.lineAt(1_000_000 - 400, 400)
    expect(end + 400 / 18).toBeCloseTo(3_000_001, 0)
    const mid = sc.scrollFor(1_500_000, 400)
    expect(sc.lineAt(mid, 400)).toBeCloseTo(1_500_000, 3)
  })
})

describe('G-code file to toolpaths', () => {
  it('reads moves, layers, features, widths and flags, each with its line', async () => {
    const ix = await indexLines(enc.encode(SAMPLE), { pause: noWait })
    const { preview: p, timeS, filamentMm } = await parseGcodePreview(ix, { pause: noWait })
    expect(p.layerCount).toBe(2)
    expect([...p.layerZ].map((z) => Math.round(z * 10) / 10)).toEqual([0.2, 0.4])
    expect(p.toolCount).toBe(2)
    expect(timeS).toBeGreaterThan(0)
    expect(filamentMm[0]).toBeCloseTo(1, 5)
    expect(filamentMm[1]).toBeGreaterThan(1.7)
    const v = new DataView(p.raw, p.segmentsOffset)
    // Layer 1: two outer wall moves, then infill in tool 1 after the wipe.
    expect(p.layerStart[1]).toBe(3)
    expect(v.getUint8(24)).toBe(FEATURE.outerWall)
    expect(v.getUint16(20, true)).toBe(450)
    expect(v.getUint8(2 * 32 + 24)).toBe(FEATURE.sparseInfill)
    expect(v.getUint8(2 * 32 + 25)).toBe(1)
    expect(lineOfSegment(p, 0)).toBe(13)
    expect(lineOfSegment(p, 2)).toBe(22)
    // The infill move starts a path after a retraction.
    const flags = new Uint8Array(p.raw, p.extrasOffset)
    expect(flags[2 * 8 + 1]! & SXPV_EXTRA_FLAG.retract).toBeTruthy()
    // The arc is drawn as chords, each on the arc's line.
    const arc = [...Array(p.segmentCount).keys()].filter((i) => lineOfSegment(p, i) === 29)
    expect(arc.length).toBeGreaterThan(10)
    expect(p.travelCount).toBeGreaterThan(0)
    expect(new Uint8Array(p.raw, p.extrasOffset)[0]).toBe(255)
    expect(new DataView(p.raw, p.extrasOffset).getUint16(2, true)).toBe(215)
  })

  it('reads the tags Orca writes for a Bambu Lab printer', async () => {
    const bambu = SAMPLE.replace(/^;LAYER_CHANGE$/gm, '; CHANGE_LAYER').replace(/^;TYPE:/gm, '; FEATURE: ').replace(/^;WIDTH:/gm, '; LINE_WIDTH: ').replace(/^;HEIGHT:/gm, '; LAYER_HEIGHT: ')
    const { preview: p } = await parseGcodePreview(await indexLines(enc.encode(bambu), { pause: noWait }), { pause: noWait })
    expect(p.layerCount).toBe(2)
    const v = new DataView(p.raw, p.segmentsOffset)
    expect(v.getUint8(24)).toBe(FEATURE.outerWall)
    expect(v.getUint16(20, true)).toBe(450)
  })

  it('names features from every slicer it knows and keeps the rest as custom', () => {
    expect(featureOf('External perimeter')).toBe(FEATURE.outerWall)
    expect(featureOf('WALL-INNER')).toBe(FEATURE.innerWall)
    expect(featureOf('support_interface')).toBe(FEATURE.supportInterface)
    expect(featureOf('Prime tower')).toBe(FEATURE.primeTower)
    expect(featureOf('something new')).toBe(FEATURE.custom)
  })

  it('links lines and moves both ways and drives the sliders', async () => {
    const ix = await indexLines(enc.encode(SAMPLE), { pause: noWait })
    const { preview: p } = await parseGcodePreview(ix, { pause: noWait })
    expect(segmentOfLine(p, 1)).toBe(-1)
    expect(segmentOfLine(p, 13)).toBe(0)
    // A comment between moves belongs to the move before it.
    expect(segmentOfLine(p, 16)).toBe(1)
    for (const seg of [0, 1, 2, 3, p.segmentCount - 1]) {
      const s = slidersFor(p, seg)
      expect(currentSegment(p, s.layerHi, s.moveCut)).toBe(seg)
      expect(layerOfSegment(p, seg)).toBe(s.layerHi - 1)
    }
    expect(currentSegment(p, 2, 1)).toBe(p.segmentCount - 1)
    expect(currentSegment(p, 0, 1)).toBe(-1)
  })

  it('finds wipes, tool and filament changes and pauses where the nozzle is', async () => {
    const ix = await indexLines(enc.encode(SAMPLE), { pause: noWait })
    const marks = await scanMarks(ix, { pause: noWait })
    expect(marks.wipes).toEqual([{ line: 16, x: 10, y: 10, z: 0.2 }])
    // The first T picks the starting tool, so only the M600 filament change counts here; the arc ended at 10, 10.
    expect(marks.toolChanges).toEqual([{ line: 30, x: 10, y: 10, z: 0.4 }])
    expect(marks.pauses).toEqual([{ line: 23, x: 0, y: 0, z: 0.2 }, { line: 31, x: 10, y: 10, z: 0.4 }])
    const two = await scanMarks(await indexLines(enc.encode('T0\nG91\nG1 X5 Y2 E1\nG1 X1\nT1\nT1\nM1\nM104 S200\nM10\n'), { pause: noWait }), { pause: noWait })
    expect(two.toolChanges).toEqual([{ line: 5, x: 6, y: 2, z: 0 }])
    expect(two.pauses.map((m) => m.line)).toEqual([7])
  })

  it('puts each marker on its layer: a wipe after its move, a pause before the next', async () => {
    const ix = await indexLines(enc.encode(SAMPLE), { pause: noWait })
    const { preview: p } = await parseGcodePreview(ix, { pause: noWait })
    const pos = positionsOf(p, await scanMarks(ix, { pause: noWait }))
    expect([...pos.wipes]).toEqual([10, 10, Math.fround(0.2)])
    // M601 at the end of layer 1 waits to print layer 2, so it shows there.
    expect([...pos.pauses.subarray(0, 3)]).toEqual([0, 0, Math.fround(0.4)])
    expect(pos.toolChanges[2]).toBeCloseTo(0.4, 5)
    // Without line numbers each marker keeps the nozzle height, and the viewport puts it on that layer.
    const bare = positionsOf({ ...p, extrasOffset: -1 }, await scanMarks(ix, { pause: noWait }))
    expect([...bare.pauses]).toEqual([0, 0, Math.fround(0.2), 10, 10, Math.fround(0.4)])
  })
})

describe('opening a G-code file', () => {
  const host = (text: string) =>
    ({ files: { read: async () => enc.encode(text).buffer } }) as unknown as Host
  const ref: FileRef = { id: 'f1', name: 'part.gcode', size: SAMPLE.length }

  it('shows the file in Slice as toolpaths without a project and puts the slice back on close', async () => {
    set({ workspace: 'prepare', slice: { status: 'idle' }, preview: null, layerHi: 0 })
    await openGcodeFile(host(SAMPLE), ref)
    const s = get()
    expect(s).toMatchObject({ workspace: 'prepare', modelMode: 'slice', sliceLook: 'toolpaths' })
    expect(s.preview?.layerCount).toBe(2)
    expect(s.layerHi).toBe(2)
    expect(gcodeView.getState().file).toMatchObject({ name: 'part.gcode', lines: 32 })
    closeFile()
    expect(gcodeView.getState().file).toBeNull()
    expect(get().preview).toBeNull()
  })

  it('lets go of the file when a slice takes Preview back', async () => {
    await openGcodeFile(host(SAMPLE), ref)
    expect(gcodeView.getState().file).not.toBeNull()
    appStore.setState({ preview: null })
    expect(gcodeView.getState().file).toBeNull()
  })

  it('says so when a file has nothing to print', async () => {
    set({ preview: null })
    await openGcodeFile(host('G28\nM104 S200\n'), ref)
    expect(get().preview).toBeNull()
    expect(get().toast?.text).toMatch(/no printing moves/)
  })
})
