// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
// The purge of each tool change, read from the G-code: matched to the timeline's changes, weighed at the
// filament's density from the file's header, and read out in the playback bar while it plays.
import { describe, expect, it } from 'vitest'
import { SXPV_HEADER_BYTES, SXPV_MAGIC, SXPV_SEGMENT_BYTES, SXPV_VERSION, readPreview, type PreviewBuffers } from '@slicerx/contracts'
import { purgeVolume, toolChangerSpec } from '@slicerx/viewport'
import { buildTimeline } from '../src/lib/preview-timeline'
import { indexLines, rangeSource } from '../src/workspaces/preview/gcode-lines'
import { plansFromText, purgeLines } from '../src/workspaces/preview/purge-data'
import { purgeReadout } from '../src/workspaces/preview/purge-view'

/** Layers of segments (x0, x1, tool) along y 0, 100 mm/s, 10 s a layer. */
function preview(layers: [number, number, number][][]): PreviewBuffers {
  const N = layers.length
  const S = layers.reduce((a, l) => a + l.length, 0)
  const raw = new ArrayBuffer(SXPV_HEADER_BYTES + (N + 1) * 4 + N * 8 + S * SXPV_SEGMENT_BYTES)
  const dv = new DataView(raw)
  dv.setUint32(0, SXPV_MAGIC, true)
  dv.setUint16(4, SXPV_VERSION, true)
  dv.setUint32(8, S, true)
  dv.setUint32(12, N, true)
  dv.setUint32(20, 4, true)
  dv.setFloat32(24, 0.2, true)
  let o = SXPV_HEADER_BYTES
  let first = 0
  layers.forEach((l, k) => {
    dv.setUint32(o + k * 4, first, true)
    first += l.length
  })
  dv.setUint32(o + N * 4, S, true)
  o += (N + 1) * 4
  layers.forEach((_, k) => dv.setFloat32(o + k * 4, 0.2 * (k + 1), true))
  o += N * 4
  layers.forEach((_, k) => dv.setFloat32(o + k * 4, 10, true))
  o += N * 4
  layers.forEach((l, k) => {
    for (const [x0, x1, tool] of l) {
      dv.setFloat32(o, x0, true)
      dv.setFloat32(o + 4, 0, true)
      dv.setFloat32(o + 8, x1, true)
      dv.setFloat32(o + 12, 0, true)
      dv.setFloat32(o + 16, 0.2 * (k + 1), true)
      dv.setUint16(o + 20, 400, true)
      dv.setUint16(o + 22, 200, true)
      dv.setUint8(o + 24, 0)
      dv.setUint8(o + 25, tool)
      dv.setUint16(o + 26, 1000, true)
      o += SXPV_SEGMENT_BYTES
    }
  })
  return readPreview(raw)
}

// An H2D with both filaments on the left nozzle, so each change is a filament change flushed at the chute.
const h2d = toolChangerSpec(
  'bambu-h2d',
  { nozzle_diameter: ['0.4', '0.4'], filament_map: ['1', '1'], machine_switch_extruder_time: '5.6', machine_load_filament_time: '26', machine_unload_filament_time: '26', travel_speed: '500', machine_max_acceleration_travel: ['9000'] },
  { widthMm: 350, depthMm: 320, heightMm: 325 },
  2,
)!

const change = (next: number, flush: number[]) => `M620 S${next}A
G1 Z3.2 F1200
M620.10 A1 F359 L${flush.reduce((a, b) => a + b, 0)} H0.4 T240 P220 S1
T${next}
;VG1 E4 F524
; VFLUSH_START
${flush.map((e) => `;VG1 E${e} F524`).join('\n')}
SYNC T10
; VFLUSH_END
M83
G1 Y295 F30000
M621 S${next}A`

const GCODE = `; HEADER_BLOCK_START
; generated by SlicerX sx-core
; filament_density: 1.24,1.31
; filament_diameter: 1.75,1.75
; HEADER_BLOCK_END
M83
T0
G1 X0 Y0 E1 F1200
G1 X10 E1
${change(1, [41.5, 100])}
G1 X30 E1
G1 X40 E1
G1 X50 E1
${change(0, [41.5, 60])}
G1 X60 E1
`

describe('purge plans from the G-code', () => {
  const p = preview([
    [[0, 10, 0], [10, 20, 0], [20, 30, 1], [30, 40, 1]],
    [[40, 50, 1], [50, 60, 0]],
  ])
  const tl = buildTimeline(p, h2d)

  it('gives each change its flush, weighed at the new filament density, starting from the filament the nozzle held', async () => {
    const ix = await indexLines(new TextEncoder().encode(GCODE))
    const plans = plansFromText(ix, p, tl, h2d)
    expect(plans.map((x) => [x.segment, x.from, x.to])).toEqual([
      [2, 0, 1],
      [5, 1, 0],
    ])
    const [a, b] = plans
    expect(a!.e).toBeCloseTo(141.5, 9)
    expect(a!.volume).toBeCloseTo(purgeVolume(141.5, 1.75), 9)
    expect(a!.grams).toBeCloseTo((a!.volume * 1.31) / 1000, 9)
    expect(b!.e).toBeCloseTo(101.5, 9)
    expect(b!.grams).toBeCloseTo((b!.volume * 1.24) / 1000, 9)
    expect(b!.before).toBeCloseTo(a!.grams, 12)
    // The flush plays at the end of the load, at the virtual moves' feed rate.
    expect(a!.window.end - a!.window.start).toBeCloseTo((141.5 / 524) * 60, 6)
  })

  it('reads out the grams of the purge in progress and the print total, only while it runs', async () => {
    const ix = await indexLines(new TextEncoder().encode(GCODE))
    const plans = plansFromText(ix, p, tl, h2d)
    const b = plans[1]!
    expect(purgeReadout(plans, null)).toBeNull()
    expect(purgeReadout(plans, { segment: b.segment, seconds: b.window.start - 0.5 })).toBeNull()
    const half = purgeReadout(plans, { segment: b.segment, seconds: (b.window.start + b.window.end) / 2 })!
    expect(half.now).toBeGreaterThan(0)
    expect(half.now).toBeLessThan(b.grams)
    expect(half.total).toBeCloseTo(plans[0]!.grams + half.now, 12)
    const done = purgeReadout(plans, { segment: b.segment, seconds: b.window.end + 1 })!
    expect(done.now).toBeCloseTo(b.grams, 12)
    expect(purgeReadout(plans, { segment: 3, seconds: 20 })).toBeNull()
  })

  it('plans the same from the lines it reads from the host that keeps the text', async () => {
    const ix = await indexLines(new TextEncoder().encode(GCODE))
    const src = rangeSource(ix.starts, (a, b) => Promise.resolve(ix.bytes.slice(a, b)))
    const { lines, toolStarts } = await purgeLines(src, p, tl)
    expect(plansFromText(lines, p, tl, h2d, toolStarts)).toEqual(plansFromText(ix, p, tl, h2d))
  })

  it('has nothing to show for a printer without a chute', async () => {
    const u1 = toolChangerSpec('snapmaker-u1', { nozzle_diameter: ['0.4', '0.4', '0.4', '0.4'], machine_tool_change_time: '5' }, { widthMm: 270, depthMm: 270, heightMm: 270 }, 4)!
    const ix = await indexLines(new TextEncoder().encode(GCODE))
    expect(plansFromText(ix, p, buildTimeline(p, u1), u1)).toEqual([])
  })
})
