// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
// @slicerx/settings. See README.md for the public API.
export { applyEasy, goalEasy, matchGoal, easyControlFor, EASY_MAP } from './easy'
export { SETTINGS, SETTING_NOTES, PROJECT_KEYS, ORCA_COMMIT, registerSettingText, clearSettingText, settingDef, settingsFor, invalidates, defaultConfig } from './schema'
export { importFlat, importOrcaProfile, exportOrcaProfile, mergeConfigs, mergeLayers, ProfileError, PROFILE_META_KEYS, LEGACY_KEYS, LEGACY_GROUPS } from './import'
export { validate, checkValues, checkConflicts, missingKeys } from './validate'
export { diffConfigs, firstStage, formatValue, sameValue, toSettingsPlan } from './diff'
export { isVisible, settingsForTier, isEnabled, failedConditions, disabledKeys, scalarOf, numberOf, widthOf } from './config'
export type { VisibilityContext, UserTier } from './config'
export { coerce, toOrca, isVectorType } from './value'
export { planSettings, applyPlan, listMaterials, listPrinters, listGoals, materialKnowledge, printerKnowledge } from './plan'
export { printerForModel, modelsForPrinter, mappedModels, setupForModel } from './printermodels'
export type { PlanOptions } from './plan'
export type { SettingText } from './schema'
export { importProject, parseXml } from './project'
export type { ProjectImport, ProjectObject, ProjectPart, LayerRange } from './project'
export { resolveAuto, AUTO_WIDTH_RATIO } from './auto'
export { HEAT_CREEP_SHARE, heatCreepWarning, layerTimeGuard } from './thinlayers'
export { smartLayerBounds, smartLayerLimits, smartLayerWindow, isSmartLayerOn, SMART_LAYER_MIN_RATIO, SMART_LAYER_MAX_RATIO, SMART_LAYER_MODE_BANDS, LAYER_STEP } from './smartlayer'
export { searchProfiles, setProfileProvider } from './profilesearch'
export type { PrinterProfileHit, ProfileProvider } from './profilesearch'
export { hasResolved, resolvedNozzles, resolvedProfile } from './resolved'
export type { ResolvedProfile } from './resolved'
export { machineEntry, gcodeStatus, listPrinterProfiles, printerProfile, printerConfig, listFilamentProfiles, filamentConfig, filamentSources, listProcessPresets, processConfig, profileConfig } from './profiles'
export type { PrinterProfile, FilamentProfile, ProcessPreset } from './profiles'
export { FILAMENT_SOURCES, filamentBrands, filamentPresetCount, listFilamentFamilies, loadFilamentPreset, loadVendorFile, resolveFilamentPreset, resolveFilamentRaw } from './filaments'
export type { FilamentFamilyInfo, FilamentPreset, VendorFile } from './filaments'
export { PRUSA_KEY_MAP, importPrusaIni, mapPrusaValues, parseIni, prusaKeyKind, prusaOverrides, prusaProjectSettings, readPrusaConfig } from './prusa'
export { buildReport, countDefaulted, defaultedText, displayRaw, displayValue, importLayers, importValues, insteadText, parentText, reasonText, reportText, settingLabel, sourceText } from './report'
export type { DropReason, Dropped, ImportLayer, ImportReport, Instead, KeyFamily, ReportInput, ReportItem, ValueSource } from './report'
export { BundleError, MAX_BUNDLE_PRESETS, MAX_PRESET_BYTES, importPresetFiles, presetKind, readPresetBundle } from './presetfile'
export type { ImportedPreset, ImportOptions, PresetBundle, PresetFile } from './presetfile'
export { printerForPresetName, printerForProfile, printerName, processForProfile, vendorParent } from './vendorparent'
export type { VendorParent } from './vendorparent'
export type { PrusaPreset } from './prusa'
export { ConditionError, evaluateCondition } from './conditions'
export { FILAMENT_LIBRARY_VENDOR, filamentsForPrinter, isCompatibleWithPrint, isCompatibleWithPrinter, libraryExclusions, printerContext } from './compat'
export type { CompatPreset, OfferedFilament, PrinterContext } from './compat'
