// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
import { describe, expect, it } from 'vitest'
import { PRUSA_KEY_MAP, importPrusaIni, mapPrusaValues, parseIni } from './prusa'
import { settingDef } from './schema'

// Small presets written for these tests; the keys and value forms follow PrusaSlicer's own file format.
const PRINT = `# generated by a test
layer_height = 0.15
first_layer_height = 0.2
perimeters = 3
top_solid_layers = 5
bottom_solid_layers = 4
fill_density = 25%
fill_pattern = gyroid
top_fill_pattern = monotonous
perimeter_speed = 50
external_perimeter_speed = 60%
small_perimeter_speed = 20
infill_speed = 120
solid_infill_speed = 80%
top_solid_infill_speed = 50%
first_layer_speed = 20
support_material = 1
support_material_auto = 1
support_material_style = organic
support_material_threshold = 40
seam_position = rear
external_perimeters_first = 1
ironing = 1
ironing_type = topmost
ironing_flowrate = 15%
gap_fill_enabled = 0
complete_objects = 0
skirts = 2
brim_width = 4
brim_separation = 0.1
perimeter_extrusion_width = 0.45
wipe_tower = 1
wipe_tower_x = 170
spiral_vase = 0
elefant_foot_compensation = 0.2
some_future_key = 3
print_settings_id = My print
`

const FILAMENT = `filament_diameter = 1.75
extrusion_multiplier = 0.98
temperature = 215
first_layer_temperature = 220
bed_temperature = 60
first_layer_bed_temperature = 65
min_fan_speed = 100
max_fan_speed = 100
bridge_fan_speed = 100
disable_fan_first_layers = 1
fan_below_layer_time = 100
filament_type = PLA
filament_colour = "#FF8000"
filament_retract_length = 0.8
start_filament_gcode = "; Filament gcode\\nM900 K0.05"
filament_settings_id = "Test PLA"
compatible_printers_condition = nozzle_diameter[0]==0.4
`

const PRINTER = `bed_shape = 0x0,250x0,250x210,0x210
max_print_height = 210
nozzle_diameter = 0.4
gcode_flavor = marlin2
retract_length = 0.8
retract_lift = 0.2
retract_speed = 35
deretract_speed = 0
travel_ramping_lift = 1
travel_max_lift = 30
start_gcode = G28 ; home\\nM104 S[first_layer_temperature]\\n
printer_notes = PRINTER_VENDOR_PRUSA3D\\nPRINTER_MODEL_TEST\\n
machine_max_feedrate_x = 200,100
machine_max_acceleration_x = 1000,960
printer_model = TEST
printer_technology = FFF
printer_settings_id = Test printer
`

describe('PrusaSlicer key map', () => {
  it('maps to keys the schema has', () => {
    for (const [from, to] of Object.entries(PRUSA_KEY_MAP)) expect(settingDef(to), `${from} -> ${to}`).toBeDefined()
  })
  it('maps a print preset', () => {
    const [p] = importPrusaIni(PRINT, 'My print.ini')
    expect(p!.section).toBe('process')
    expect(p!.name).toBe('My print')
    const c = p!.config as Record<string, unknown>
    expect(c['layer_height']).toBe(0.15)
    expect(c['initial_layer_print_height']).toBe(0.2)
    expect(c['wall_loops']).toBe(3)
    expect(c['top_shell_layers']).toBe(5)
    expect(c['bottom_shell_layers']).toBe(4)
    expect(c['sparse_infill_density']).toBe(25)
    expect(c['sparse_infill_pattern']).toBe('gyroid')
    expect(c['top_surface_pattern']).toBe('monotonic')
    expect(c['inner_wall_speed']).toEqual([50])
    expect(c['outer_wall_speed']).toEqual([30])
    expect(c['sparse_infill_speed']).toEqual([120])
    expect(c['internal_solid_infill_speed']).toEqual([96])
    expect(c['top_surface_speed']).toEqual([48])
    expect(c['initial_layer_speed']).toEqual([20])
    expect(c['enable_support']).toBe(true)
    expect(c['support_type']).toBe('tree(auto)')
    expect(c['support_threshold_angle']).toBe(40)
    expect(c['seam_position']).toBe('back')
    expect(c['wall_sequence']).toBe('outer wall/inner wall')
    expect(c['ironing_type']).toBe('topmost')
    expect(c['ironing_flow']).toBe(15)
    expect(c['gap_fill_target']).toBe('nowhere')
    expect(c['print_sequence']).toBe('by layer')
    expect(c['skirt_loops']).toBe(2)
    expect(c['brim_width']).toBe(4)
    expect(c['brim_object_gap']).toBe(0.1)
    expect(c['inner_wall_line_width']).toBe('0.45')
    expect(c['enable_prime_tower']).toBe(true)
    expect(c['spiral_mode']).toBe(false)
    expect(c['elefant_foot_compensation']).toBe(0.2)
    expect(p!.unmappedKeys).toEqual(['some_future_key'])
    expect(p!.ignoredKeys).toEqual(['print_settings_id', 'wipe_tower_x'])
    expect(p!.invalidKeys).toEqual([])
  })
  it('turns ironing off when the switch is off and falls back to top when no type is given', () => {
    expect(mapPrusaValues({ ironing: '0', ironing_type: 'solid' }).values['ironing_type']).toBe('no ironing')
    expect(mapPrusaValues({ ironing: '1' }).values['ironing_type']).toBe('top')
  })
  it('scales the first layer speed by percent from the preset speeds', () => {
    const v = mapPrusaValues({ first_layer_speed: '50%', perimeter_speed: '40', infill_speed: '100' }).values
    expect(v['initial_layer_speed']).toBe('20')
    expect(v['initial_layer_infill_speed']).toBe('50')
  })
  it('maps a filament preset', () => {
    const [p] = importPrusaIni(FILAMENT, 'pla.ini')
    expect(p!.section).toBe('filament')
    expect(p!.name).toBe('Test PLA')
    const c = p!.config as Record<string, unknown>
    expect(c['filament_diameter']).toEqual([1.75])
    expect(c['filament_flow_ratio']).toEqual([0.98])
    expect(c['nozzle_temperature']).toEqual([215])
    expect(c['nozzle_temperature_initial_layer']).toEqual([220])
    expect(c['hot_plate_temp']).toEqual([60])
    expect(c['textured_plate_temp_initial_layer']).toEqual([65])
    expect(c['fan_min_speed']).toEqual([100])
    expect(c['close_fan_the_first_x_layers']).toEqual([1])
    expect(c['fan_cooling_layer_time']).toEqual([100])
    expect(c['default_filament_colour']).toEqual(['#FF8000'])
    expect(c['filament_retraction_length']).toEqual([0.8])
    expect(c['filament_start_gcode']).toEqual(['; Filament gcode\nM900 K0.05'])
    expect(c['compatible_printers_condition']).toBe('nozzle_diameter[0]==0.4')
    expect(p!.unmappedKeys).toEqual([])
  })
  it('maps a printer preset', () => {
    const [p] = importPrusaIni(PRINTER, 'mk.ini')
    expect(p!.section).toBe('printer')
    const c = p!.config as Record<string, unknown>
    expect(c['printable_area']).toEqual([[0, 0], [250, 0], [250, 210], [0, 210]])
    expect(c['printable_height']).toBe(210)
    expect(c['gcode_flavor']).toBe('marlin2')
    expect(c['retraction_length']).toEqual([0.8])
    expect(c['z_hop']).toEqual([0.2])
    expect(c['retraction_speed']).toEqual([35])
    expect(c['z_hop_types']).toEqual(['Slope Lift'])
    expect(c['travel_slope']).toEqual([30])
    expect(c['machine_start_gcode']).toBe('G28 ; home\nM104 S[first_layer_temperature]\n')
    expect(c['printer_notes']).toBe('PRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_TEST\n')
    expect(c['machine_max_speed_x']).toEqual([200, 100])
    expect(c['machine_max_acceleration_x']).toEqual([1000, 960])
    expect(p!.unmappedKeys).toEqual([])
  })
  it('splits an exported configuration into one preset per kind', () => {
    const all = importPrusaIni(`${PRINT}${FILAMENT}${PRINTER}`, 'config.ini')
    expect(all.map((p) => p.section)).toEqual(['process', 'filament', 'printer'])
    expect(all.map((p) => p.name)).toEqual(['My print', 'Test PLA', 'Test printer'])
    expect((all[0]!.config as Record<string, unknown>)['nozzle_temperature']).toBeUndefined()
  })
  it('reads a config bundle and merges inherits chains, dropping abstract sections', () => {
    const bundle = `[presets]\nprint = Fast\n\n[print:*common*]\nperimeters = 2\nlayer_height = 0.2\nfill_density = 10%\n\n[print:*draft*]\ninherits = *common*\nlayer_height = 0.3\n\n[print:Fast]\ninherits = *draft*\nfill_density = 5%\n\n[filament:Plain PLA]\ntemperature = 210\ncompatible_printers = "Printer A";"Printer B"\n\n[printer:Printer A]\nbed_shape = 0x0,100x0,100x100,0x100\n`
    const out = importPrusaIni(bundle)
    expect(out.map((p) => `${p.section}:${p.name}`)).toEqual(['process:Fast', 'filament:Plain PLA', 'printer:Printer A'])
    const c = out[0]!.config as Record<string, unknown>
    expect(c['layer_height']).toBe(0.3)
    expect(c['wall_loops']).toBe(2)
    expect(c['sparse_infill_density']).toBe(5)
    expect(out[0]!.inherits).toEqual(['*draft*'])
    expect((out[1]!.config as Record<string, unknown>)['compatible_printers']).toEqual(['Printer A', 'Printer B'])
  })
  it('ignores SLA keys and reports the rest as unmapped', () => {
    const m = mapPrusaValues({ layer_height: '0.1', exposure_time: '8', pad_enable: '1', display_width: '120', infill_every_layers: '2', top_one_perimeter_type: 'none' })
    expect(m.ignored).toEqual(['display_width', 'exposure_time', 'pad_enable'])
    expect(m.unmapped).toEqual(['infill_every_layers', 'top_one_perimeter_type'])
  })
  it('parses ini lines, comments and quoted lists', () => {
    expect(parseIni('# c\n[a:b]\nx = 1\n; d\ny = "p";"q;r"\n')).toEqual([{ type: 'a', name: 'b', values: { x: '1', y: '"p";"q;r"' } }])
  })
})
