// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
//! `sx slice --request` and `sx schema`: the CLI's JSON surface.

use std::io::Write;
use std::process::{Command, Stdio};

fn sx() -> Command {
    Command::new(env!("CARGO_BIN_EXE_sx"))
}

fn fixture(name: &str) -> String {
    format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"))
}

#[test]
fn request_file_round_trip() {
    let dir = std::env::temp_dir().join(format!("sx-cli-test-{}", std::process::id()));
    let out = sx()
        .args(["slice", "--request", &fixture("cube-request.json"), "--out-dir"])
        .arg(&dir)
        .output()
        .unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(v["schemaVersion"], 1);
    assert_eq!(v["engine"], "sx");
    assert_eq!(v["layerCount"], 50);
    assert_eq!(v["layerZ"].as_array().unwrap().len(), 50);
    let gcode = std::fs::read(dir.join("slice.gcode")).unwrap();
    assert_eq!(v["gcodeBytes"], gcode.len());
    assert!(String::from_utf8_lossy(&gcode).contains("SET_PRINT_STATS_INFO TOTAL_LAYER=50"));
    let _ = std::fs::remove_dir_all(dir);
}

#[test]
fn request_from_stdin_and_bad_input() {
    let body = std::fs::read_to_string(fixture("cube-request.json"))
        .unwrap()
        .replace("\"cube.stl\"", &format!("{:?}", fixture("cube.stl")));
    let mut child = sx()
        .args(["slice", "--request", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.take().unwrap().write_all(body.as_bytes()).unwrap();
    let out = child.wait_with_output().unwrap();
    assert!(out.status.success());
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(v["gcodeSha256"].as_str().unwrap().len(), 64);

    let mut child = sx()
        .args(["slice", "--request", "-"])
        .stdin(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.take().unwrap().write_all(b"{\"plate\":").unwrap();
    assert_eq!(child.wait_with_output().unwrap().status.code(), Some(3));
}

#[test]
fn schemas_are_json() {
    for which in ["request", "result"] {
        let out = sx().args(["schema", which]).output().unwrap();
        let v: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
        assert_eq!(v["$schema"], "https://json-schema.org/draft/2020-12/schema");
    }
    assert_eq!(
        sx().args(["schema", "nope"]).output().unwrap().status.code(),
        Some(2)
    );
}

#[test]
fn slice_stdout_is_only_gcode() {
    let out = sx().args(["slice", &fixture("cube.stl")]).output().unwrap();
    assert!(out.status.success());
    let text = String::from_utf8(out.stdout).unwrap();
    assert!(
        text.starts_with("; generated by SlicerX"),
        "{}",
        &text[..40.min(text.len())]
    );
    assert!(sx_core::extras::LAYER_MARKS.iter().any(|m| text.contains(m)));
    assert!(String::from_utf8_lossy(&out.stderr).contains("50 layers"));
}

#[test]
fn metadata_of_a_plain_3mf_is_empty() {
    let path = format!("{}/../bench/models/x-mark-2color.3mf", env!("CARGO_MANIFEST_DIR"));
    let out = sx().args(["metadata", &path]).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert!(v.get("modelSettings").is_some());
    assert!(v.get("projectSettings").is_none());
    assert_eq!(
        sx().args(["metadata", &fixture("cube.stl")])
            .output()
            .unwrap()
            .status
            .code(),
        Some(1)
    );
}

/// A Bambu Studio project's own settings, as `sx metadata` hands them over, slice with its -1s for auto
/// (bambu-auto.3mf: a 20 mm cube and the negative values Bambu Studio writes).
#[test]
fn a_bambu_projects_auto_values_slice() {
    let path = fixture("bambu-auto.3mf");
    let out = sx().args(["metadata", &path]).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let meta: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let settings = meta["projectSettings"].clone();
    assert_eq!(settings["raft_first_layer_expansion"], "-1");
    let dir = std::env::temp_dir().join(format!("sx-cli-bambu-auto-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let run = |extra: &[(&str, &str)]| {
        let mut config = settings.clone();
        for (k, v) in extra {
            config[*k] = serde_json::Value::String((*v).to_owned());
        }
        let req = serde_json::json!({
            "schemaVersion": 1,
            "meshes": {"p": path},
            "plate": {"objects": [{"id": "p", "mesh": "p"}]},
            "config": config,
        });
        let file = dir.join("request.json");
        std::fs::write(&file, req.to_string()).unwrap();
        sx().args(["slice", "--request"]).arg(&file).output().unwrap()
    };
    // no raft, no supports, then a raft that grows its first layer on auto
    for extra in [&[][..], &[("raft_layers", "2")][..]] {
        let out = run(extra);
        assert!(
            out.status.success(),
            "{extra:?}: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        let v: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
        assert!(v["layerCount"].as_u64().unwrap() > 90, "{v}");
    }
    let _ = std::fs::remove_dir_all(dir);
}

/// A 3MF plate given as one mesh prints as its objects: by object each one finishes before the
/// next starts, and objects too close for the toolhead are refused as bad input.
#[test]
fn a_3mf_plate_slices_as_its_objects() {
    let dir = std::env::temp_dir().join(format!("sx-cli-3mf-objects-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let run = |radius: u32, rod: u32, allow: bool| {
        let req = serde_json::json!({
            "schemaVersion": 1,
            "meshes": {"p": fixture("two-boxes.3mf")},
            "plate": {"objects": [{"id": "p", "mesh": "p"}]},
            "config": {
                "print_sequence": "by object", "layer_height": 0.2, "initial_layer_print_height": 0.2,
                "brim_width": 0, "skirt_loops": 0, "extruder_clearance_radius": radius,
                "extruder_clearance_height_to_rod": rod
            },
        });
        let path = dir.join(format!("request-{radius}-{rod}.json"));
        std::fs::write(&path, req.to_string()).unwrap();
        let mut cmd = sx();
        cmd.args(["slice", "--request"]).arg(&path);
        if allow {
            cmd.arg("--allow-collisions");
        }
        cmd.output().unwrap()
    };
    // a 10 mm and a 4 mm box, 80 mm apart: one after the other, so 50 and 20 layers
    let out = run(40, 40, false);
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(v["layerCount"], 70);
    assert!(v.get("collisions").is_none());
    // closer than a 90 mm radius, but the head itself clears: sliced, with the close call listed
    let out = run(90, 40, false);
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(v["collisions"][0]["severity"], "close");
    // a gantry 3 mm over the nozzle passes through the 10 mm box while the 4 mm one prints: refused
    let out = run(40, 3, false);
    assert_eq!(out.status.code(), Some(3));
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(
        err.contains("printing by object is not safe: The gantry hits tall."),
        "{err}"
    );
    // the fixes the engine offers, and the way past the refusal
    // both boxes stand over the 3 mm gantry, so no order clears it: printing by layer does
    assert!(err.contains("To fix it: print by layer."), "{err}");
    assert!(
        err.contains("To slice it anyway, add --allow-collisions."),
        "{err}"
    );
    assert!(run(40, 3, true).status.success());
    let _ = std::fs::remove_dir_all(dir);
}

/// Paths into a zone the printer keeps clear are the plate's own, in any print order: refused in their own words,
/// not as a by-object clearance.
#[test]
fn keep_out_paths_are_refused_in_their_own_words() {
    let mut req: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(fixture("features-request.json")).unwrap()).unwrap();
    req["meshes"]["c"] = serde_json::Value::String(fixture("cube.stl"));
    req["meshes"]["t"] = serde_json::Value::String(fixture("table.stl"));
    // an A1 style nozzle wrap check corner over the cube
    req["config"]["head_wrap_detect_zone"] = serde_json::json!(["80x95", "115x95", "115x125", "80x125"]);
    let dir = std::env::temp_dir().join(format!("sx-cli-keep-out-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("request.json");
    std::fs::write(&path, req.to_string()).unwrap();
    let out = sx().args(["slice", "--request"]).arg(&path).output().unwrap();
    assert_eq!(out.status.code(), Some(3));
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(
        err.contains("A print path or travel enters the nozzle wrap check corner: c1 on layers 1 to"),
        "{err}"
    );
    assert!(!err.contains("printing by object"), "{err}");
    let out = sx()
        .args(["slice", "--request"])
        .arg(&path)
        .arg("--allow-collisions")
        .output()
        .unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let _ = std::fs::remove_dir_all(dir);
}

#[test]
fn untrusted_start_gcode_names_the_preflight_once() {
    let mut req: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(fixture("cube-request.json")).unwrap()).unwrap();
    req["meshes"]["cube"] = serde_json::Value::String(fixture("cube.stl"));
    req["config"]["machine_start_gcode"] = serde_json::Value::String("G28\nM500 ; save\n".to_owned());
    let mut child = sx()
        .args(["slice", "--request", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child
        .stdin
        .take()
        .unwrap()
        .write_all(req.to_string().as_bytes())
        .unwrap();
    let out = child.wait_with_output().unwrap();
    assert_eq!(out.status.code(), Some(1));
    assert_eq!(
        String::from_utf8_lossy(&out.stderr).trim_end(),
        "sx slice: blocked by the safety preflight: custom G-code: line 2: M500 writes settings to the printer's memory (eeprom_write)"
    );
}

/// The stock start G-code `SlicerX` ships for a printer (packages/profiles/gcode.json), as a Bambu project saves it.
fn shipped_start(model: &str) -> String {
    let doc: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/../../profiles/gcode.json")).unwrap(),
    )
    .unwrap();
    let family = doc["models"][model].as_str().unwrap();
    doc["families"][family]["start"].as_str().unwrap().to_owned()
}

fn slice_with(config: &[(&str, serde_json::Value)], options: &serde_json::Value) -> std::process::Output {
    let mut req: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(fixture("cube-request.json")).unwrap()).unwrap();
    req["meshes"]["cube"] = serde_json::Value::String(fixture("cube.stl"));
    for (k, v) in config {
        req["config"][*k] = v.clone();
    }
    for (k, v) in options.as_object().into_iter().flatten() {
        req["options"][k] = v.clone();
    }
    let mut child = sx()
        .args(["slice", "--request", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child
        .stdin
        .take()
        .unwrap()
        .write_all(req.to_string().as_bytes())
        .unwrap();
    child.wait_with_output().unwrap()
}

#[cfg(feature = "stock-gcode")]
#[test]
fn a_projects_stock_start_gcode_runs_as_the_maker_wrote_it() {
    let p1s = shipped_start("bambu-p1s");
    assert!(
        p1s.lines().any(|l| l.trim_start().starts_with("M500")),
        "the P1S start saves calibration data"
    );
    // Named the way a Bambu project names its printer, by profile or by model.
    for name in [
        ("printer_settings_id", "Bambu Lab P1S 0.4 nozzle"),
        ("printer_model", "Bambu Lab P1S"),
        ("inherits", "Bambu Lab P1S 0.6 nozzle"),
    ] {
        let out = slice_with(
            &[
                (name.0, serde_json::Value::String(name.1.to_owned())),
                (
                    "machine_start_gcode",
                    serde_json::Value::String(p1s.replace('\n', "\r\n")),
                ),
            ],
            &serde_json::json!({}),
        );
        assert!(
            out.status.success(),
            "{name:?}: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }
}

#[test]
fn stock_text_is_trusted_only_for_its_own_printer_and_only_as_written() {
    let p1s = shipped_start("bambu-p1s");
    let blocked = |out: &std::process::Output| {
        assert_eq!(
            out.status.code(),
            Some(1),
            "{}",
            String::from_utf8_lossy(&out.stderr)
        );
        let err = String::from_utf8_lossy(&out.stderr);
        assert_eq!(err.matches("blocked by the safety preflight").count(), 1, "{err}");
        assert!(
            err.contains("M500 writes settings to the printer's memory"),
            "{err}"
        );
    };
    let model = (
        "printer_model",
        serde_json::Value::String("Bambu Lab X1 Carbon".to_owned()),
    );
    let start = ("machine_start_gcode", serde_json::Value::String(p1s.clone()));
    blocked(&slice_with(&[model, start], &serde_json::json!({})));
    let edited = format!("{p1s}\nG1 X10\n");
    let model = (
        "printer_model",
        serde_json::Value::String("Bambu Lab P1S".to_owned()),
    );
    blocked(&slice_with(
        &[model, ("machine_start_gcode", serde_json::Value::String(edited))],
        &serde_json::json!({}),
    ));
}

#[test]
fn a_line_no_one_can_approve_stays_blocked_when_trusted() {
    let out = slice_with(
        &[(
            "machine_start_gcode",
            serde_json::Value::String("G28\nM502\n".to_owned()),
        )],
        &serde_json::json!({ "trustedGcode": true }),
    );
    assert_eq!(out.status.code(), Some(1));
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(
        err.contains("M502 resets the printer to factory settings"),
        "{err}"
    );
    assert_eq!(err.matches("blocked by the safety preflight").count(), 1, "{err}");
}
