// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The SlicerX contributors
//! `sx slice --request` and `sx schema`: the CLI's JSON surface.

use std::io::Write;
use std::process::{Command, Stdio};

fn sx() -> Command {
    Command::new(env!("CARGO_BIN_EXE_sx"))
}

fn fixture(name: &str) -> String {
    format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"))
}

#[test]
fn request_file_round_trip() {
    let dir = std::env::temp_dir().join(format!("sx-cli-test-{}", std::process::id()));
    let out = sx()
        .args(["slice", "--request", &fixture("cube-request.json"), "--out-dir"])
        .arg(&dir)
        .output()
        .unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(v["schemaVersion"], 1);
    assert_eq!(v["engine"], "sx");
    assert_eq!(v["layerCount"], 50);
    assert_eq!(v["layerZ"].as_array().unwrap().len(), 50);
    let gcode = std::fs::read(dir.join("slice.gcode")).unwrap();
    assert_eq!(v["gcodeBytes"], gcode.len());
    assert!(String::from_utf8_lossy(&gcode).contains("SET_PRINT_STATS_INFO TOTAL_LAYER=50"));
    let _ = std::fs::remove_dir_all(dir);
}

#[test]
fn request_from_stdin_and_bad_input() {
    let body = std::fs::read_to_string(fixture("cube-request.json"))
        .unwrap()
        .replace("\"cube.stl\"", &format!("{:?}", fixture("cube.stl")));
    let mut child = sx()
        .args(["slice", "--request", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.take().unwrap().write_all(body.as_bytes()).unwrap();
    let out = child.wait_with_output().unwrap();
    assert!(out.status.success());
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(v["gcodeSha256"].as_str().unwrap().len(), 64);

    let mut child = sx()
        .args(["slice", "--request", "-"])
        .stdin(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.take().unwrap().write_all(b"{\"plate\":").unwrap();
    assert_eq!(child.wait_with_output().unwrap().status.code(), Some(3));
}

#[test]
fn schemas_are_json() {
    for which in ["request", "result"] {
        let out = sx().args(["schema", which]).output().unwrap();
        let v: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
        assert_eq!(v["$schema"], "https://json-schema.org/draft/2020-12/schema");
    }
    assert_eq!(
        sx().args(["schema", "nope"]).output().unwrap().status.code(),
        Some(2)
    );
}

#[test]
fn slice_stdout_is_only_gcode() {
    let out = sx().args(["slice", &fixture("cube.stl")]).output().unwrap();
    assert!(out.status.success());
    let text = String::from_utf8(out.stdout).unwrap();
    assert!(
        text.starts_with("; generated by SlicerX"),
        "{}",
        &text[..40.min(text.len())]
    );
    assert!(sx_core::extras::LAYER_MARKS.iter().any(|m| text.contains(m)));
    assert!(String::from_utf8_lossy(&out.stderr).contains("50 layers"));
}

#[test]
fn metadata_of_a_plain_3mf_is_empty() {
    let path = format!("{}/../bench/models/x-mark-2color.3mf", env!("CARGO_MANIFEST_DIR"));
    let out = sx().args(["metadata", &path]).output().unwrap();
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert!(v.get("modelSettings").is_some());
    assert!(v.get("projectSettings").is_none());
    assert_eq!(
        sx().args(["metadata", &fixture("cube.stl")])
            .output()
            .unwrap()
            .status
            .code(),
        Some(1)
    );
}

/// A 3MF plate given as one mesh prints as its objects: by object each one finishes before the
/// next starts, and objects too close for the toolhead are refused as bad input.
#[test]
fn a_3mf_plate_slices_as_its_objects() {
    let dir = std::env::temp_dir().join(format!("sx-cli-3mf-objects-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let run = |radius: u32| {
        let req = serde_json::json!({
            "schemaVersion": 1,
            "meshes": {"p": fixture("two-boxes.3mf")},
            "plate": {"objects": [{"id": "p", "mesh": "p"}]},
            "config": {
                "print_sequence": "by object", "layer_height": 0.2, "initial_layer_print_height": 0.2,
                "brim_width": 0, "skirt_loops": 0, "extruder_clearance_radius": radius
            },
        });
        let path = dir.join(format!("request-{radius}.json"));
        std::fs::write(&path, req.to_string()).unwrap();
        sx().args(["slice", "--request"]).arg(&path).output().unwrap()
    };
    // a 10 mm and a 4 mm box, 80 mm apart: one after the other, so 50 and 20 layers
    let out = run(40);
    assert!(out.status.success(), "{}", String::from_utf8_lossy(&out.stderr));
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(v["layerCount"], 70);
    let out = run(90);
    assert_eq!(out.status.code(), Some(3));
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(
        err.contains("printing by object is not safe: tall and short are 80.0 mm apart"),
        "{err}"
    );
    let _ = std::fs::remove_dir_all(dir);
}
