#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 The SlicerX contributors
# Regenerates src/generated/database.ts from the local Supabase stack.
set -eu
cd "$(dirname "$0")/.."
out=src/generated/database.ts
tmp="$out.tmp"
{
  # REUSE-IgnoreStart
  echo '// SPDX-License-Identifier: Apache-2.0'
  # REUSE-IgnoreEnd
  echo '// Copyright (C) 2026 The SlicerX contributors'
  echo '// Generated by `pnpm --filter @slicerx/store gen:types` from the local stack. Do not edit by hand.'
  (cd ../.. && supabase gen types typescript --local --schema public)
} > "$tmp"
mv "$tmp" "$out"
